package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGameUsedPlan;
import com.cheyooh.service.sdk.db.entity.SdkGameUsedPlanExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGameUsedPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    int countByExample(SdkGameUsedPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGameUsedPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    int insert(SdkGameUsedPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    int insertSelective(SdkGameUsedPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    List<SdkGameUsedPlan> selectByExample(SdkGameUsedPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    Pagination<SdkGameUsedPlan> selectByExample(SdkGameUsedPlanExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    SdkGameUsedPlan selectOne(SdkGameUsedPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    SdkGameUsedPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGameUsedPlan record, @Param("example") SdkGameUsedPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGameUsedPlan record, @Param("example") SdkGameUsedPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGameUsedPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_used_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGameUsedPlan record);
}