package com.cheyooh.service.sdk.db.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SdkOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    public SdkOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("order_no =", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("order_no <>", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("order_no >", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("order_no >=", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoLessThan(String value) {
            addCriterion("order_no <", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("order_no <=", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoLike(String value) {
            addCriterion("order_no like", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoNotLike(String value) {
            addCriterion("order_no not like", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("order_no in", values, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("order_no not in", values, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("order_no between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("order_no not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNameIsNull() {
            addCriterion("order_name is null");
            return (Criteria) this;
        }

        public Criteria andOrderNameIsNotNull() {
            addCriterion("order_name is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单名称
        */
        public Criteria andOrderNameEqualTo(String value) {
            addCriterion("order_name =", value, "orderName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单名称
        */
        public Criteria andOrderNameNotEqualTo(String value) {
            addCriterion("order_name <>", value, "orderName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单名称
        */
        public Criteria andOrderNameGreaterThan(String value) {
            addCriterion("order_name >", value, "orderName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单名称
        */
        public Criteria andOrderNameGreaterThanOrEqualTo(String value) {
            addCriterion("order_name >=", value, "orderName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单名称
        */
        public Criteria andOrderNameLessThan(String value) {
            addCriterion("order_name <", value, "orderName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单名称
        */
        public Criteria andOrderNameLessThanOrEqualTo(String value) {
            addCriterion("order_name <=", value, "orderName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单名称
        */
        public Criteria andOrderNameLike(String value) {
            addCriterion("order_name like", value, "orderName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单名称
        */
        public Criteria andOrderNameNotLike(String value) {
            addCriterion("order_name not like", value, "orderName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单名称
        */
        public Criteria andOrderNameIn(List<String> values) {
            addCriterion("order_name in", values, "orderName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单名称
        */
        public Criteria andOrderNameNotIn(List<String> values) {
            addCriterion("order_name not in", values, "orderName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单名称
        */
        public Criteria andOrderNameBetween(String value1, String value2) {
            addCriterion("order_name between", value1, value2, "orderName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单名称
        */
        public Criteria andOrderNameNotBetween(String value1, String value2) {
            addCriterion("order_name not between", value1, value2, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderDescIsNull() {
            addCriterion("order_desc is null");
            return (Criteria) this;
        }

        public Criteria andOrderDescIsNotNull() {
            addCriterion("order_desc is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单描述
        */
        public Criteria andOrderDescEqualTo(String value) {
            addCriterion("order_desc =", value, "orderDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单描述
        */
        public Criteria andOrderDescNotEqualTo(String value) {
            addCriterion("order_desc <>", value, "orderDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单描述
        */
        public Criteria andOrderDescGreaterThan(String value) {
            addCriterion("order_desc >", value, "orderDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单描述
        */
        public Criteria andOrderDescGreaterThanOrEqualTo(String value) {
            addCriterion("order_desc >=", value, "orderDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单描述
        */
        public Criteria andOrderDescLessThan(String value) {
            addCriterion("order_desc <", value, "orderDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单描述
        */
        public Criteria andOrderDescLessThanOrEqualTo(String value) {
            addCriterion("order_desc <=", value, "orderDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单描述
        */
        public Criteria andOrderDescLike(String value) {
            addCriterion("order_desc like", value, "orderDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单描述
        */
        public Criteria andOrderDescNotLike(String value) {
            addCriterion("order_desc not like", value, "orderDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单描述
        */
        public Criteria andOrderDescIn(List<String> values) {
            addCriterion("order_desc in", values, "orderDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单描述
        */
        public Criteria andOrderDescNotIn(List<String> values) {
            addCriterion("order_desc not in", values, "orderDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单描述
        */
        public Criteria andOrderDescBetween(String value1, String value2) {
            addCriterion("order_desc between", value1, value2, "orderDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单描述
        */
        public Criteria andOrderDescNotBetween(String value1, String value2) {
            addCriterion("order_desc not between", value1, value2, "orderDesc");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("`uid` is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("`uid` is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 用户ID
        */
        public Criteria andUidEqualTo(Integer value) {
            addCriterion("`uid` =", value, "uid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 用户ID
        */
        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("`uid` <>", value, "uid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 用户ID
        */
        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("`uid` >", value, "uid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 用户ID
        */
        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("`uid` >=", value, "uid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 用户ID
        */
        public Criteria andUidLessThan(Integer value) {
            addCriterion("`uid` <", value, "uid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 用户ID
        */
        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("`uid` <=", value, "uid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 用户ID
        */
        public Criteria andUidIn(List<Integer> values) {
            addCriterion("`uid` in", values, "uid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 用户ID
        */
        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("`uid` not in", values, "uid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 用户ID
        */
        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("`uid` between", value1, value2, "uid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 用户ID
        */
        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("`uid` not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 充值方式:
1- 支付宝
2- 财付通
3- 易宝(充值卡)
4- MO9
5- 微派

        */
        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 充值方式:
1- 支付宝
2- 财付通
3- 易宝(充值卡)
4- MO9
5- 微派

        */
        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 充值方式:
1- 支付宝
2- 财付通
3- 易宝(充值卡)
4- MO9
5- 微派

        */
        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 充值方式:
1- 支付宝
2- 财付通
3- 易宝(充值卡)
4- MO9
5- 微派

        */
        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 充值方式:
1- 支付宝
2- 财付通
3- 易宝(充值卡)
4- MO9
5- 微派

        */
        public Criteria andTypeLessThan(Integer value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 充值方式:
1- 支付宝
2- 财付通
3- 易宝(充值卡)
4- MO9
5- 微派

        */
        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 充值方式:
1- 支付宝
2- 财付通
3- 易宝(充值卡)
4- MO9
5- 微派

        */
        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 充值方式:
1- 支付宝
2- 财付通
3- 易宝(充值卡)
4- MO9
5- 微派

        */
        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 充值方式:
1- 支付宝
2- 财付通
3- 易宝(充值卡)
4- MO9
5- 微派

        */
        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 充值方式:
1- 支付宝
2- 财付通
3- 易宝(充值卡)
4- MO9
5- 微派

        */
        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPayIdIsNull() {
            addCriterion("pay_id is null");
            return (Criteria) this;
        }

        public Criteria andPayIdIsNotNull() {
            addCriterion("pay_id is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付记录ID(根据recharge_type字段,对应具体支付表的主键)
        */
        public Criteria andPayIdEqualTo(Integer value) {
            addCriterion("pay_id =", value, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付记录ID(根据recharge_type字段,对应具体支付表的主键)
        */
        public Criteria andPayIdNotEqualTo(Integer value) {
            addCriterion("pay_id <>", value, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付记录ID(根据recharge_type字段,对应具体支付表的主键)
        */
        public Criteria andPayIdGreaterThan(Integer value) {
            addCriterion("pay_id >", value, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付记录ID(根据recharge_type字段,对应具体支付表的主键)
        */
        public Criteria andPayIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_id >=", value, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付记录ID(根据recharge_type字段,对应具体支付表的主键)
        */
        public Criteria andPayIdLessThan(Integer value) {
            addCriterion("pay_id <", value, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付记录ID(根据recharge_type字段,对应具体支付表的主键)
        */
        public Criteria andPayIdLessThanOrEqualTo(Integer value) {
            addCriterion("pay_id <=", value, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付记录ID(根据recharge_type字段,对应具体支付表的主键)
        */
        public Criteria andPayIdIn(List<Integer> values) {
            addCriterion("pay_id in", values, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付记录ID(根据recharge_type字段,对应具体支付表的主键)
        */
        public Criteria andPayIdNotIn(List<Integer> values) {
            addCriterion("pay_id not in", values, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付记录ID(根据recharge_type字段,对应具体支付表的主键)
        */
        public Criteria andPayIdBetween(Integer value1, Integer value2) {
            addCriterion("pay_id between", value1, value2, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付记录ID(根据recharge_type字段,对应具体支付表的主键)
        */
        public Criteria andPayIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_id not between", value1, value2, "payId");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单金额(单位元)
        */
        public Criteria andAmountEqualTo(Float value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单金额(单位元)
        */
        public Criteria andAmountNotEqualTo(Float value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单金额(单位元)
        */
        public Criteria andAmountGreaterThan(Float value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单金额(单位元)
        */
        public Criteria andAmountGreaterThanOrEqualTo(Float value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单金额(单位元)
        */
        public Criteria andAmountLessThan(Float value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单金额(单位元)
        */
        public Criteria andAmountLessThanOrEqualTo(Float value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单金额(单位元)
        */
        public Criteria andAmountIn(List<Float> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单金额(单位元)
        */
        public Criteria andAmountNotIn(List<Float> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单金额(单位元)
        */
        public Criteria andAmountBetween(Float value1, Float value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单金额(单位元)
        */
        public Criteria andAmountNotBetween(Float value1, Float value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andCpIdIsNull() {
            addCriterion("cp_id is null");
            return (Criteria) this;
        }

        public Criteria andCpIdIsNotNull() {
            addCriterion("cp_id is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏商ID
        */
        public Criteria andCpIdEqualTo(Integer value) {
            addCriterion("cp_id =", value, "cpId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏商ID
        */
        public Criteria andCpIdNotEqualTo(Integer value) {
            addCriterion("cp_id <>", value, "cpId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏商ID
        */
        public Criteria andCpIdGreaterThan(Integer value) {
            addCriterion("cp_id >", value, "cpId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏商ID
        */
        public Criteria andCpIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cp_id >=", value, "cpId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏商ID
        */
        public Criteria andCpIdLessThan(Integer value) {
            addCriterion("cp_id <", value, "cpId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏商ID
        */
        public Criteria andCpIdLessThanOrEqualTo(Integer value) {
            addCriterion("cp_id <=", value, "cpId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏商ID
        */
        public Criteria andCpIdIn(List<Integer> values) {
            addCriterion("cp_id in", values, "cpId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏商ID
        */
        public Criteria andCpIdNotIn(List<Integer> values) {
            addCriterion("cp_id not in", values, "cpId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏商ID
        */
        public Criteria andCpIdBetween(Integer value1, Integer value2) {
            addCriterion("cp_id between", value1, value2, "cpId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏商ID
        */
        public Criteria andCpIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cp_id not between", value1, value2, "cpId");
            return (Criteria) this;
        }

        public Criteria andGameIdIsNull() {
            addCriterion("game_id is null");
            return (Criteria) this;
        }

        public Criteria andGameIdIsNotNull() {
            addCriterion("game_id is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏ID
        */
        public Criteria andGameIdEqualTo(Integer value) {
            addCriterion("game_id =", value, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏ID
        */
        public Criteria andGameIdNotEqualTo(Integer value) {
            addCriterion("game_id <>", value, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏ID
        */
        public Criteria andGameIdGreaterThan(Integer value) {
            addCriterion("game_id >", value, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏ID
        */
        public Criteria andGameIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("game_id >=", value, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏ID
        */
        public Criteria andGameIdLessThan(Integer value) {
            addCriterion("game_id <", value, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏ID
        */
        public Criteria andGameIdLessThanOrEqualTo(Integer value) {
            addCriterion("game_id <=", value, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏ID
        */
        public Criteria andGameIdIn(List<Integer> values) {
            addCriterion("game_id in", values, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏ID
        */
        public Criteria andGameIdNotIn(List<Integer> values) {
            addCriterion("game_id not in", values, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏ID
        */
        public Criteria andGameIdBetween(Integer value1, Integer value2) {
            addCriterion("game_id between", value1, value2, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏ID
        */
        public Criteria andGameIdNotBetween(Integer value1, Integer value2) {
            addCriterion("game_id not between", value1, value2, "gameId");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("channel is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("channel is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andChannelEqualTo(String value) {
            addCriterion("channel =", value, "channel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("channel <>", value, "channel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andChannelGreaterThan(String value) {
            addCriterion("channel >", value, "channel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("channel >=", value, "channel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andChannelLessThan(String value) {
            addCriterion("channel <", value, "channel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("channel <=", value, "channel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andChannelLike(String value) {
            addCriterion("channel like", value, "channel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andChannelNotLike(String value) {
            addCriterion("channel not like", value, "channel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andChannelIn(List<String> values) {
            addCriterion("channel in", values, "channel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("channel not in", values, "channel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("channel between", value1, value2, "channel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("channel not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单状态:
0-订单创建, 
1-支付成功, 
2-等待结果, 
3-支付失败,
4-订单异常
        */
        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单状态:
0-订单创建, 
1-支付成功, 
2-等待结果, 
3-支付失败,
4-订单异常
        */
        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单状态:
0-订单创建, 
1-支付成功, 
2-等待结果, 
3-支付失败,
4-订单异常
        */
        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单状态:
0-订单创建, 
1-支付成功, 
2-等待结果, 
3-支付失败,
4-订单异常
        */
        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单状态:
0-订单创建, 
1-支付成功, 
2-等待结果, 
3-支付失败,
4-订单异常
        */
        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单状态:
0-订单创建, 
1-支付成功, 
2-等待结果, 
3-支付失败,
4-订单异常
        */
        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单状态:
0-订单创建, 
1-支付成功, 
2-等待结果, 
3-支付失败,
4-订单异常
        */
        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单状态:
0-订单创建, 
1-支付成功, 
2-等待结果, 
3-支付失败,
4-订单异常
        */
        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单状态:
0-订单创建, 
1-支付成功, 
2-等待结果, 
3-支付失败,
4-订单异常
        */
        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单状态:
0-订单创建, 
1-支付成功, 
2-等待结果, 
3-支付失败,
4-订单异常
        */
        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusDetailIsNull() {
            addCriterion("status_detail is null");
            return (Criteria) this;
        }

        public Criteria andStatusDetailIsNotNull() {
            addCriterion("status_detail is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 状态进一步描述(如错误或异常的原因)
        */
        public Criteria andStatusDetailEqualTo(String value) {
            addCriterion("status_detail =", value, "statusDetail");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 状态进一步描述(如错误或异常的原因)
        */
        public Criteria andStatusDetailNotEqualTo(String value) {
            addCriterion("status_detail <>", value, "statusDetail");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 状态进一步描述(如错误或异常的原因)
        */
        public Criteria andStatusDetailGreaterThan(String value) {
            addCriterion("status_detail >", value, "statusDetail");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 状态进一步描述(如错误或异常的原因)
        */
        public Criteria andStatusDetailGreaterThanOrEqualTo(String value) {
            addCriterion("status_detail >=", value, "statusDetail");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 状态进一步描述(如错误或异常的原因)
        */
        public Criteria andStatusDetailLessThan(String value) {
            addCriterion("status_detail <", value, "statusDetail");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 状态进一步描述(如错误或异常的原因)
        */
        public Criteria andStatusDetailLessThanOrEqualTo(String value) {
            addCriterion("status_detail <=", value, "statusDetail");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 状态进一步描述(如错误或异常的原因)
        */
        public Criteria andStatusDetailLike(String value) {
            addCriterion("status_detail like", value, "statusDetail");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 状态进一步描述(如错误或异常的原因)
        */
        public Criteria andStatusDetailNotLike(String value) {
            addCriterion("status_detail not like", value, "statusDetail");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 状态进一步描述(如错误或异常的原因)
        */
        public Criteria andStatusDetailIn(List<String> values) {
            addCriterion("status_detail in", values, "statusDetail");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 状态进一步描述(如错误或异常的原因)
        */
        public Criteria andStatusDetailNotIn(List<String> values) {
            addCriterion("status_detail not in", values, "statusDetail");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 状态进一步描述(如错误或异常的原因)
        */
        public Criteria andStatusDetailBetween(String value1, String value2) {
            addCriterion("status_detail between", value1, value2, "statusDetail");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 状态进一步描述(如错误或异常的原因)
        */
        public Criteria andStatusDetailNotBetween(String value1, String value2) {
            addCriterion("status_detail not between", value1, value2, "statusDetail");
            return (Criteria) this;
        }

        public Criteria andCpExtIsNull() {
            addCriterion("cp_ext is null");
            return (Criteria) this;
        }

        public Criteria andCpExtIsNotNull() {
            addCriterion("cp_ext is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏服务商扩展信息
        */
        public Criteria andCpExtEqualTo(String value) {
            addCriterion("cp_ext =", value, "cpExt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏服务商扩展信息
        */
        public Criteria andCpExtNotEqualTo(String value) {
            addCriterion("cp_ext <>", value, "cpExt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏服务商扩展信息
        */
        public Criteria andCpExtGreaterThan(String value) {
            addCriterion("cp_ext >", value, "cpExt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏服务商扩展信息
        */
        public Criteria andCpExtGreaterThanOrEqualTo(String value) {
            addCriterion("cp_ext >=", value, "cpExt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏服务商扩展信息
        */
        public Criteria andCpExtLessThan(String value) {
            addCriterion("cp_ext <", value, "cpExt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏服务商扩展信息
        */
        public Criteria andCpExtLessThanOrEqualTo(String value) {
            addCriterion("cp_ext <=", value, "cpExt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏服务商扩展信息
        */
        public Criteria andCpExtLike(String value) {
            addCriterion("cp_ext like", value, "cpExt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏服务商扩展信息
        */
        public Criteria andCpExtNotLike(String value) {
            addCriterion("cp_ext not like", value, "cpExt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏服务商扩展信息
        */
        public Criteria andCpExtIn(List<String> values) {
            addCriterion("cp_ext in", values, "cpExt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏服务商扩展信息
        */
        public Criteria andCpExtNotIn(List<String> values) {
            addCriterion("cp_ext not in", values, "cpExt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏服务商扩展信息
        */
        public Criteria andCpExtBetween(String value1, String value2) {
            addCriterion("cp_ext between", value1, value2, "cpExt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏服务商扩展信息
        */
        public Criteria andCpExtNotBetween(String value1, String value2) {
            addCriterion("cp_ext not between", value1, value2, "cpExt");
            return (Criteria) this;
        }

        public Criteria andQueryStatusIsNull() {
            addCriterion("query_status is null");
            return (Criteria) this;
        }

        public Criteria andQueryStatusIsNotNull() {
            addCriterion("query_status is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryStatusEqualTo(Integer value) {
            addCriterion("query_status =", value, "queryStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryStatusNotEqualTo(Integer value) {
            addCriterion("query_status <>", value, "queryStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryStatusGreaterThan(Integer value) {
            addCriterion("query_status >", value, "queryStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("query_status >=", value, "queryStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryStatusLessThan(Integer value) {
            addCriterion("query_status <", value, "queryStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryStatusLessThanOrEqualTo(Integer value) {
            addCriterion("query_status <=", value, "queryStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryStatusIn(List<Integer> values) {
            addCriterion("query_status in", values, "queryStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryStatusNotIn(List<Integer> values) {
            addCriterion("query_status not in", values, "queryStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryStatusBetween(Integer value1, Integer value2) {
            addCriterion("query_status between", value1, value2, "queryStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("query_status not between", value1, value2, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryTimeIsNull() {
            addCriterion("query_time is null");
            return (Criteria) this;
        }

        public Criteria andQueryTimeIsNotNull() {
            addCriterion("query_time is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryTimeEqualTo(Date value) {
            addCriterion("query_time =", value, "queryTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryTimeNotEqualTo(Date value) {
            addCriterion("query_time <>", value, "queryTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryTimeGreaterThan(Date value) {
            addCriterion("query_time >", value, "queryTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("query_time >=", value, "queryTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryTimeLessThan(Date value) {
            addCriterion("query_time <", value, "queryTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryTimeLessThanOrEqualTo(Date value) {
            addCriterion("query_time <=", value, "queryTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryTimeIn(List<Date> values) {
            addCriterion("query_time in", values, "queryTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryTimeNotIn(List<Date> values) {
            addCriterion("query_time not in", values, "queryTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryTimeBetween(Date value1, Date value2) {
            addCriterion("query_time between", value1, value2, "queryTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andQueryTimeNotBetween(Date value1, Date value2) {
            addCriterion("query_time not between", value1, value2, "queryTime");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusIsNull() {
            addCriterion("notify_status is null");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusIsNotNull() {
            addCriterion("notify_status is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单通知状态:
0-尚未通知
1-成功通知
2-通知失败
3-无需通知
<0-通知失败的次数

        */
        public Criteria andNotifyStatusEqualTo(Integer value) {
            addCriterion("notify_status =", value, "notifyStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单通知状态:
0-尚未通知
1-成功通知
2-通知失败
3-无需通知
<0-通知失败的次数

        */
        public Criteria andNotifyStatusNotEqualTo(Integer value) {
            addCriterion("notify_status <>", value, "notifyStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单通知状态:
0-尚未通知
1-成功通知
2-通知失败
3-无需通知
<0-通知失败的次数

        */
        public Criteria andNotifyStatusGreaterThan(Integer value) {
            addCriterion("notify_status >", value, "notifyStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单通知状态:
0-尚未通知
1-成功通知
2-通知失败
3-无需通知
<0-通知失败的次数

        */
        public Criteria andNotifyStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("notify_status >=", value, "notifyStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单通知状态:
0-尚未通知
1-成功通知
2-通知失败
3-无需通知
<0-通知失败的次数

        */
        public Criteria andNotifyStatusLessThan(Integer value) {
            addCriterion("notify_status <", value, "notifyStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单通知状态:
0-尚未通知
1-成功通知
2-通知失败
3-无需通知
<0-通知失败的次数

        */
        public Criteria andNotifyStatusLessThanOrEqualTo(Integer value) {
            addCriterion("notify_status <=", value, "notifyStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单通知状态:
0-尚未通知
1-成功通知
2-通知失败
3-无需通知
<0-通知失败的次数

        */
        public Criteria andNotifyStatusIn(List<Integer> values) {
            addCriterion("notify_status in", values, "notifyStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单通知状态:
0-尚未通知
1-成功通知
2-通知失败
3-无需通知
<0-通知失败的次数

        */
        public Criteria andNotifyStatusNotIn(List<Integer> values) {
            addCriterion("notify_status not in", values, "notifyStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单通知状态:
0-尚未通知
1-成功通知
2-通知失败
3-无需通知
<0-通知失败的次数

        */
        public Criteria andNotifyStatusBetween(Integer value1, Integer value2) {
            addCriterion("notify_status between", value1, value2, "notifyStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单通知状态:
0-尚未通知
1-成功通知
2-通知失败
3-无需通知
<0-通知失败的次数

        */
        public Criteria andNotifyStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("notify_status not between", value1, value2, "notifyStatus");
            return (Criteria) this;
        }

        public Criteria andNotifyRequestIsNull() {
            addCriterion("notify_request is null");
            return (Criteria) this;
        }

        public Criteria andNotifyRequestIsNotNull() {
            addCriterion("notify_request is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求URL(包括请求参数, 用于后台管理手动重发)
        */
        public Criteria andNotifyRequestEqualTo(String value) {
            addCriterion("notify_request =", value, "notifyRequest");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求URL(包括请求参数, 用于后台管理手动重发)
        */
        public Criteria andNotifyRequestNotEqualTo(String value) {
            addCriterion("notify_request <>", value, "notifyRequest");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求URL(包括请求参数, 用于后台管理手动重发)
        */
        public Criteria andNotifyRequestGreaterThan(String value) {
            addCriterion("notify_request >", value, "notifyRequest");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求URL(包括请求参数, 用于后台管理手动重发)
        */
        public Criteria andNotifyRequestGreaterThanOrEqualTo(String value) {
            addCriterion("notify_request >=", value, "notifyRequest");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求URL(包括请求参数, 用于后台管理手动重发)
        */
        public Criteria andNotifyRequestLessThan(String value) {
            addCriterion("notify_request <", value, "notifyRequest");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求URL(包括请求参数, 用于后台管理手动重发)
        */
        public Criteria andNotifyRequestLessThanOrEqualTo(String value) {
            addCriterion("notify_request <=", value, "notifyRequest");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求URL(包括请求参数, 用于后台管理手动重发)
        */
        public Criteria andNotifyRequestLike(String value) {
            addCriterion("notify_request like", value, "notifyRequest");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求URL(包括请求参数, 用于后台管理手动重发)
        */
        public Criteria andNotifyRequestNotLike(String value) {
            addCriterion("notify_request not like", value, "notifyRequest");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求URL(包括请求参数, 用于后台管理手动重发)
        */
        public Criteria andNotifyRequestIn(List<String> values) {
            addCriterion("notify_request in", values, "notifyRequest");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求URL(包括请求参数, 用于后台管理手动重发)
        */
        public Criteria andNotifyRequestNotIn(List<String> values) {
            addCriterion("notify_request not in", values, "notifyRequest");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求URL(包括请求参数, 用于后台管理手动重发)
        */
        public Criteria andNotifyRequestBetween(String value1, String value2) {
            addCriterion("notify_request between", value1, value2, "notifyRequest");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求URL(包括请求参数, 用于后台管理手动重发)
        */
        public Criteria andNotifyRequestNotBetween(String value1, String value2) {
            addCriterion("notify_request not between", value1, value2, "notifyRequest");
            return (Criteria) this;
        }

        public Criteria andNotifyResponseIsNull() {
            addCriterion("notify_response is null");
            return (Criteria) this;
        }

        public Criteria andNotifyResponseIsNotNull() {
            addCriterion("notify_response is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 最后一次通知游戏服务器响应的信息
        */
        public Criteria andNotifyResponseEqualTo(String value) {
            addCriterion("notify_response =", value, "notifyResponse");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 最后一次通知游戏服务器响应的信息
        */
        public Criteria andNotifyResponseNotEqualTo(String value) {
            addCriterion("notify_response <>", value, "notifyResponse");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 最后一次通知游戏服务器响应的信息
        */
        public Criteria andNotifyResponseGreaterThan(String value) {
            addCriterion("notify_response >", value, "notifyResponse");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 最后一次通知游戏服务器响应的信息
        */
        public Criteria andNotifyResponseGreaterThanOrEqualTo(String value) {
            addCriterion("notify_response >=", value, "notifyResponse");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 最后一次通知游戏服务器响应的信息
        */
        public Criteria andNotifyResponseLessThan(String value) {
            addCriterion("notify_response <", value, "notifyResponse");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 最后一次通知游戏服务器响应的信息
        */
        public Criteria andNotifyResponseLessThanOrEqualTo(String value) {
            addCriterion("notify_response <=", value, "notifyResponse");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 最后一次通知游戏服务器响应的信息
        */
        public Criteria andNotifyResponseLike(String value) {
            addCriterion("notify_response like", value, "notifyResponse");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 最后一次通知游戏服务器响应的信息
        */
        public Criteria andNotifyResponseNotLike(String value) {
            addCriterion("notify_response not like", value, "notifyResponse");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 最后一次通知游戏服务器响应的信息
        */
        public Criteria andNotifyResponseIn(List<String> values) {
            addCriterion("notify_response in", values, "notifyResponse");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 最后一次通知游戏服务器响应的信息
        */
        public Criteria andNotifyResponseNotIn(List<String> values) {
            addCriterion("notify_response not in", values, "notifyResponse");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 最后一次通知游戏服务器响应的信息
        */
        public Criteria andNotifyResponseBetween(String value1, String value2) {
            addCriterion("notify_response between", value1, value2, "notifyResponse");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 最后一次通知游戏服务器响应的信息
        */
        public Criteria andNotifyResponseNotBetween(String value1, String value2) {
            addCriterion("notify_response not between", value1, value2, "notifyResponse");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeIsNull() {
            addCriterion("notify_time is null");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeIsNotNull() {
            addCriterion("notify_time is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 上一次通知的时间
        */
        public Criteria andNotifyTimeEqualTo(Date value) {
            addCriterion("notify_time =", value, "notifyTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 上一次通知的时间
        */
        public Criteria andNotifyTimeNotEqualTo(Date value) {
            addCriterion("notify_time <>", value, "notifyTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 上一次通知的时间
        */
        public Criteria andNotifyTimeGreaterThan(Date value) {
            addCriterion("notify_time >", value, "notifyTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 上一次通知的时间
        */
        public Criteria andNotifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("notify_time >=", value, "notifyTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 上一次通知的时间
        */
        public Criteria andNotifyTimeLessThan(Date value) {
            addCriterion("notify_time <", value, "notifyTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 上一次通知的时间
        */
        public Criteria andNotifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("notify_time <=", value, "notifyTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 上一次通知的时间
        */
        public Criteria andNotifyTimeIn(List<Date> values) {
            addCriterion("notify_time in", values, "notifyTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 上一次通知的时间
        */
        public Criteria andNotifyTimeNotIn(List<Date> values) {
            addCriterion("notify_time not in", values, "notifyTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 上一次通知的时间
        */
        public Criteria andNotifyTimeBetween(Date value1, Date value2) {
            addCriterion("notify_time between", value1, value2, "notifyTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 上一次通知的时间
        */
        public Criteria andNotifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("notify_time not between", value1, value2, "notifyTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIsNull() {
            addCriterion("complete_time is null");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIsNotNull() {
            addCriterion("complete_time is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单完成时间
        */
        public Criteria andCompleteTimeEqualTo(Date value) {
            addCriterion("complete_time =", value, "completeTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单完成时间
        */
        public Criteria andCompleteTimeNotEqualTo(Date value) {
            addCriterion("complete_time <>", value, "completeTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单完成时间
        */
        public Criteria andCompleteTimeGreaterThan(Date value) {
            addCriterion("complete_time >", value, "completeTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单完成时间
        */
        public Criteria andCompleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("complete_time >=", value, "completeTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单完成时间
        */
        public Criteria andCompleteTimeLessThan(Date value) {
            addCriterion("complete_time <", value, "completeTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单完成时间
        */
        public Criteria andCompleteTimeLessThanOrEqualTo(Date value) {
            addCriterion("complete_time <=", value, "completeTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单完成时间
        */
        public Criteria andCompleteTimeIn(List<Date> values) {
            addCriterion("complete_time in", values, "completeTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单完成时间
        */
        public Criteria andCompleteTimeNotIn(List<Date> values) {
            addCriterion("complete_time not in", values, "completeTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单完成时间
        */
        public Criteria andCompleteTimeBetween(Date value1, Date value2) {
            addCriterion("complete_time between", value1, value2, "completeTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单完成时间
        */
        public Criteria andCompleteTimeNotBetween(Date value1, Date value2) {
            addCriterion("complete_time not between", value1, value2, "completeTime");
            return (Criteria) this;
        }

        public Criteria andOriginalcodeIsNull() {
            addCriterion("originalcode is null");
            return (Criteria) this;
        }

        public Criteria andOriginalcodeIsNotNull() {
            addCriterion("originalcode is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeEqualTo(String value) {
            addCriterion("originalcode =", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeNotEqualTo(String value) {
            addCriterion("originalcode <>", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeGreaterThan(String value) {
            addCriterion("originalcode >", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeGreaterThanOrEqualTo(String value) {
            addCriterion("originalcode >=", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeLessThan(String value) {
            addCriterion("originalcode <", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeLessThanOrEqualTo(String value) {
            addCriterion("originalcode <=", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeLike(String value) {
            addCriterion("originalcode like", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeNotLike(String value) {
            addCriterion("originalcode not like", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeIn(List<String> values) {
            addCriterion("originalcode in", values, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeNotIn(List<String> values) {
            addCriterion("originalcode not in", values, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeBetween(String value1, String value2) {
            addCriterion("originalcode between", value1, value2, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeNotBetween(String value1, String value2) {
            addCriterion("originalcode not between", value1, value2, "originalcode");
            return (Criteria) this;
        }

        public Criteria andSdkverIsNull() {
            addCriterion("sdkver is null");
            return (Criteria) this;
        }

        public Criteria andSdkverIsNotNull() {
            addCriterion("sdkver is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: sdk版本号
        */
        public Criteria andSdkverEqualTo(String value) {
            addCriterion("sdkver =", value, "sdkver");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: sdk版本号
        */
        public Criteria andSdkverNotEqualTo(String value) {
            addCriterion("sdkver <>", value, "sdkver");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: sdk版本号
        */
        public Criteria andSdkverGreaterThan(String value) {
            addCriterion("sdkver >", value, "sdkver");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: sdk版本号
        */
        public Criteria andSdkverGreaterThanOrEqualTo(String value) {
            addCriterion("sdkver >=", value, "sdkver");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: sdk版本号
        */
        public Criteria andSdkverLessThan(String value) {
            addCriterion("sdkver <", value, "sdkver");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: sdk版本号
        */
        public Criteria andSdkverLessThanOrEqualTo(String value) {
            addCriterion("sdkver <=", value, "sdkver");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: sdk版本号
        */
        public Criteria andSdkverLike(String value) {
            addCriterion("sdkver like", value, "sdkver");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: sdk版本号
        */
        public Criteria andSdkverNotLike(String value) {
            addCriterion("sdkver not like", value, "sdkver");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: sdk版本号
        */
        public Criteria andSdkverIn(List<String> values) {
            addCriterion("sdkver in", values, "sdkver");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: sdk版本号
        */
        public Criteria andSdkverNotIn(List<String> values) {
            addCriterion("sdkver not in", values, "sdkver");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: sdk版本号
        */
        public Criteria andSdkverBetween(String value1, String value2) {
            addCriterion("sdkver between", value1, value2, "sdkver");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: sdk版本号
        */
        public Criteria andSdkverNotBetween(String value1, String value2) {
            addCriterion("sdkver not between", value1, value2, "sdkver");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIsNull() {
            addCriterion("operation_type is null");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIsNotNull() {
            addCriterion("operation_type is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeEqualTo(Integer value) {
            addCriterion("operation_type =", value, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeNotEqualTo(Integer value) {
            addCriterion("operation_type <>", value, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeGreaterThan(Integer value) {
            addCriterion("operation_type >", value, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("operation_type >=", value, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeLessThan(Integer value) {
            addCriterion("operation_type <", value, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeLessThanOrEqualTo(Integer value) {
            addCriterion("operation_type <=", value, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeIn(List<Integer> values) {
            addCriterion("operation_type in", values, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeNotIn(List<Integer> values) {
            addCriterion("operation_type not in", values, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeBetween(Integer value1, Integer value2) {
            addCriterion("operation_type between", value1, value2, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("operation_type not between", value1, value2, "operationType");
            return (Criteria) this;
        }

        public Criteria andMobilephoneIsNull() {
            addCriterion("mobilephone is null");
            return (Criteria) this;
        }

        public Criteria andMobilephoneIsNotNull() {
            addCriterion("mobilephone is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号码
        */
        public Criteria andMobilephoneEqualTo(String value) {
            addCriterion("mobilephone =", value, "mobilephone");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号码
        */
        public Criteria andMobilephoneNotEqualTo(String value) {
            addCriterion("mobilephone <>", value, "mobilephone");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号码
        */
        public Criteria andMobilephoneGreaterThan(String value) {
            addCriterion("mobilephone >", value, "mobilephone");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号码
        */
        public Criteria andMobilephoneGreaterThanOrEqualTo(String value) {
            addCriterion("mobilephone >=", value, "mobilephone");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号码
        */
        public Criteria andMobilephoneLessThan(String value) {
            addCriterion("mobilephone <", value, "mobilephone");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号码
        */
        public Criteria andMobilephoneLessThanOrEqualTo(String value) {
            addCriterion("mobilephone <=", value, "mobilephone");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号码
        */
        public Criteria andMobilephoneLike(String value) {
            addCriterion("mobilephone like", value, "mobilephone");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号码
        */
        public Criteria andMobilephoneNotLike(String value) {
            addCriterion("mobilephone not like", value, "mobilephone");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号码
        */
        public Criteria andMobilephoneIn(List<String> values) {
            addCriterion("mobilephone in", values, "mobilephone");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号码
        */
        public Criteria andMobilephoneNotIn(List<String> values) {
            addCriterion("mobilephone not in", values, "mobilephone");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号码
        */
        public Criteria andMobilephoneBetween(String value1, String value2) {
            addCriterion("mobilephone between", value1, value2, "mobilephone");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号码
        */
        public Criteria andMobilephoneNotBetween(String value1, String value2) {
            addCriterion("mobilephone not between", value1, value2, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andProvinceNoIsNull() {
            addCriterion("province_no is null");
            return (Criteria) this;
        }

        public Criteria andProvinceNoIsNotNull() {
            addCriterion("province_no is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 省份地址编码
        */
        public Criteria andProvinceNoEqualTo(Integer value) {
            addCriterion("province_no =", value, "provinceNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 省份地址编码
        */
        public Criteria andProvinceNoNotEqualTo(Integer value) {
            addCriterion("province_no <>", value, "provinceNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 省份地址编码
        */
        public Criteria andProvinceNoGreaterThan(Integer value) {
            addCriterion("province_no >", value, "provinceNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 省份地址编码
        */
        public Criteria andProvinceNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("province_no >=", value, "provinceNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 省份地址编码
        */
        public Criteria andProvinceNoLessThan(Integer value) {
            addCriterion("province_no <", value, "provinceNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 省份地址编码
        */
        public Criteria andProvinceNoLessThanOrEqualTo(Integer value) {
            addCriterion("province_no <=", value, "provinceNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 省份地址编码
        */
        public Criteria andProvinceNoIn(List<Integer> values) {
            addCriterion("province_no in", values, "provinceNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 省份地址编码
        */
        public Criteria andProvinceNoNotIn(List<Integer> values) {
            addCriterion("province_no not in", values, "provinceNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 省份地址编码
        */
        public Criteria andProvinceNoBetween(Integer value1, Integer value2) {
            addCriterion("province_no between", value1, value2, "provinceNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 省份地址编码
        */
        public Criteria andProvinceNoNotBetween(Integer value1, Integer value2) {
            addCriterion("province_no not between", value1, value2, "provinceNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_order
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion() {
            super();
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}