package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGameAdvertisementList;
import com.cheyooh.service.sdk.db.entity.SdkGameAdvertisementListExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGameAdvertisementListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    int countByExample(SdkGameAdvertisementListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGameAdvertisementListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    int insert(SdkGameAdvertisementList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    int insertSelective(SdkGameAdvertisementList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    List<SdkGameAdvertisementList> selectByExample(SdkGameAdvertisementListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    Pagination<SdkGameAdvertisementList> selectByExample(SdkGameAdvertisementListExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    SdkGameAdvertisementList selectOne(SdkGameAdvertisementListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    SdkGameAdvertisementList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGameAdvertisementList record, @Param("example") SdkGameAdvertisementListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGameAdvertisementList record, @Param("example") SdkGameAdvertisementListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGameAdvertisementList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_advertisement_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGameAdvertisementList record);
}