package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkPayment;
import com.cheyooh.service.sdk.db.entity.SdkPaymentExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    int countByExample(SdkPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    int deleteByExample(SdkPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    int insert(SdkPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    int insertSelective(SdkPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    List<SdkPayment> selectByExample(SdkPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    Pagination<SdkPayment> selectByExample(SdkPaymentExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    SdkPayment selectOne(SdkPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    SdkPayment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkPayment record, @Param("example") SdkPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkPayment record, @Param("example") SdkPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_payment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkPayment record);
}