package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkWoplusOfflinePaySms;
import com.cheyooh.service.sdk.db.entity.SdkWoplusOfflinePaySmsExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkWoplusOfflinePaySmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    int countByExample(SdkWoplusOfflinePaySmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    int deleteByExample(SdkWoplusOfflinePaySmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    int insert(SdkWoplusOfflinePaySms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    int insertSelective(SdkWoplusOfflinePaySms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    List<SdkWoplusOfflinePaySms> selectByExample(SdkWoplusOfflinePaySmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    Pagination<SdkWoplusOfflinePaySms> selectByExample(SdkWoplusOfflinePaySmsExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    SdkWoplusOfflinePaySms selectOne(SdkWoplusOfflinePaySmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    SdkWoplusOfflinePaySms selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkWoplusOfflinePaySms record, @Param("example") SdkWoplusOfflinePaySmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkWoplusOfflinePaySms record, @Param("example") SdkWoplusOfflinePaySmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkWoplusOfflinePaySms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_woplus_offline_pay_sms
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkWoplusOfflinePaySms record);
}