package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkUserLoginGame;
import com.cheyooh.service.sdk.db.entity.SdkUserLoginGameExample;
import com.cheyooh.service.sdk.db.entity.SdkUserLoginGameKey;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkUserLoginGameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    int countByExample(SdkUserLoginGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    int deleteByExample(SdkUserLoginGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SdkUserLoginGameKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    int insert(SdkUserLoginGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    int insertSelective(SdkUserLoginGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    List<SdkUserLoginGame> selectByExample(SdkUserLoginGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    Pagination<SdkUserLoginGame> selectByExample(SdkUserLoginGameExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    SdkUserLoginGame selectOne(SdkUserLoginGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    SdkUserLoginGame selectByPrimaryKey(SdkUserLoginGameKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkUserLoginGame record, @Param("example") SdkUserLoginGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkUserLoginGame record, @Param("example") SdkUserLoginGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkUserLoginGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_user_login_game
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkUserLoginGame record);
}