package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkOrderYeepay;
import com.cheyooh.service.sdk.db.entity.SdkOrderYeepayExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkOrderYeepayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    int countByExample(SdkOrderYeepayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    int deleteByExample(SdkOrderYeepayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    int insert(SdkOrderYeepay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    int insertSelective(SdkOrderYeepay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    List<SdkOrderYeepay> selectByExample(SdkOrderYeepayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    Pagination<SdkOrderYeepay> selectByExample(SdkOrderYeepayExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    SdkOrderYeepay selectOne(SdkOrderYeepayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    SdkOrderYeepay selectByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkOrderYeepay record, @Param("example") SdkOrderYeepayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkOrderYeepay record, @Param("example") SdkOrderYeepayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkOrderYeepay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_yeepay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkOrderYeepay record);
}