package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkMmdoShield;
import com.cheyooh.service.sdk.db.entity.SdkMmdoShieldExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkMmdoShieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    int countByExample(SdkMmdoShieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    int deleteByExample(SdkMmdoShieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    int insert(SdkMmdoShield record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    int insertSelective(SdkMmdoShield record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    List<SdkMmdoShield> selectByExample(SdkMmdoShieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    Pagination<SdkMmdoShield> selectByExample(SdkMmdoShieldExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    SdkMmdoShield selectOne(SdkMmdoShieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    SdkMmdoShield selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkMmdoShield record, @Param("example") SdkMmdoShieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkMmdoShield record, @Param("example") SdkMmdoShieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkMmdoShield record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mmdo_shield
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkMmdoShield record);
}