package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkBulletin;
import com.cheyooh.service.sdk.db.entity.SdkBulletinExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkBulletinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    int countByExample(SdkBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    int deleteByExample(SdkBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer bulletinId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    int insert(SdkBulletin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    int insertSelective(SdkBulletin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    List<SdkBulletin> selectByExample(SdkBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    Pagination<SdkBulletin> selectByExample(SdkBulletinExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    SdkBulletin selectOne(SdkBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    SdkBulletin selectByPrimaryKey(Integer bulletinId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkBulletin record, @Param("example") SdkBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkBulletin record, @Param("example") SdkBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkBulletin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_bulletin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkBulletin record);
}