package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkNotifyMmdo;
import com.cheyooh.service.sdk.db.entity.SdkNotifyMmdoExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkNotifyMmdoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    int countByExample(SdkNotifyMmdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    int deleteByExample(SdkNotifyMmdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    int insert(SdkNotifyMmdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    int insertSelective(SdkNotifyMmdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    List<SdkNotifyMmdo> selectByExample(SdkNotifyMmdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    Pagination<SdkNotifyMmdo> selectByExample(SdkNotifyMmdoExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    SdkNotifyMmdo selectOne(SdkNotifyMmdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    SdkNotifyMmdo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkNotifyMmdo record, @Param("example") SdkNotifyMmdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkNotifyMmdo record, @Param("example") SdkNotifyMmdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkNotifyMmdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_mmdo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkNotifyMmdo record);
}