package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkWiipayPaycode;
import com.cheyooh.service.sdk.db.entity.SdkWiipayPaycodeExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkWiipayPaycodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    int countByExample(SdkWiipayPaycodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    int deleteByExample(SdkWiipayPaycodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    int insert(SdkWiipayPaycode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    int insertSelective(SdkWiipayPaycode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    List<SdkWiipayPaycode> selectByExample(SdkWiipayPaycodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    Pagination<SdkWiipayPaycode> selectByExample(SdkWiipayPaycodeExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    SdkWiipayPaycode selectOne(SdkWiipayPaycodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    SdkWiipayPaycode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkWiipayPaycode record, @Param("example") SdkWiipayPaycodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkWiipayPaycode record, @Param("example") SdkWiipayPaycodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkWiipayPaycode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_wiipay_paycode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkWiipayPaycode record);
}