package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkUpgrade;
import com.cheyooh.service.sdk.db.entity.SdkUpgradeExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkUpgradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    int countByExample(SdkUpgradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    int deleteByExample(SdkUpgradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer upgradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    int insert(SdkUpgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    int insertSelective(SdkUpgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    List<SdkUpgrade> selectByExample(SdkUpgradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    Pagination<SdkUpgrade> selectByExample(SdkUpgradeExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    SdkUpgrade selectOne(SdkUpgradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    SdkUpgrade selectByPrimaryKey(Integer upgradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkUpgrade record, @Param("example") SdkUpgradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkUpgrade record, @Param("example") SdkUpgradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkUpgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkUpgrade record);
}