package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkProps;
import com.cheyooh.service.sdk.db.entity.SdkPropsExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkPropsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    int countByExample(SdkPropsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    int deleteByExample(SdkPropsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    int insert(SdkProps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    int insertSelective(SdkProps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    List<SdkProps> selectByExample(SdkPropsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    Pagination<SdkProps> selectByExample(SdkPropsExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    SdkProps selectOne(SdkPropsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    SdkProps selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkProps record, @Param("example") SdkPropsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkProps record, @Param("example") SdkPropsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkProps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkProps record);
}