package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkDanglesdkPoint;
import com.cheyooh.service.sdk.db.entity.SdkDanglesdkPointExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkDanglesdkPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    int countByExample(SdkDanglesdkPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    int deleteByExample(SdkDanglesdkPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    int insert(SdkDanglesdkPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    int insertSelective(SdkDanglesdkPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    List<SdkDanglesdkPoint> selectByExample(SdkDanglesdkPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    Pagination<SdkDanglesdkPoint> selectByExample(SdkDanglesdkPointExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    SdkDanglesdkPoint selectOne(SdkDanglesdkPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    SdkDanglesdkPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkDanglesdkPoint record, @Param("example") SdkDanglesdkPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkDanglesdkPoint record, @Param("example") SdkDanglesdkPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkDanglesdkPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_danglesdk_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkDanglesdkPoint record);
}