package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkNotifyXiaomisdk;
import com.cheyooh.service.sdk.db.entity.SdkNotifyXiaomisdkExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkNotifyXiaomisdkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    int countByExample(SdkNotifyXiaomisdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    int deleteByExample(SdkNotifyXiaomisdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    int insert(SdkNotifyXiaomisdk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    int insertSelective(SdkNotifyXiaomisdk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    List<SdkNotifyXiaomisdk> selectByExample(SdkNotifyXiaomisdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    Pagination<SdkNotifyXiaomisdk> selectByExample(SdkNotifyXiaomisdkExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    SdkNotifyXiaomisdk selectOne(SdkNotifyXiaomisdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    SdkNotifyXiaomisdk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkNotifyXiaomisdk record, @Param("example") SdkNotifyXiaomisdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkNotifyXiaomisdk record, @Param("example") SdkNotifyXiaomisdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkNotifyXiaomisdk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_xiaomisdk
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkNotifyXiaomisdk record);
}