package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGiftVcode;
import com.cheyooh.service.sdk.db.entity.SdkGiftVcodeExample;
import com.cheyooh.service.sdk.db.entity.SdkGiftVcodeKey;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGiftVcodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    int countByExample(SdkGiftVcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGiftVcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SdkGiftVcodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    int insert(SdkGiftVcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    int insertSelective(SdkGiftVcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    List<SdkGiftVcode> selectByExample(SdkGiftVcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    Pagination<SdkGiftVcode> selectByExample(SdkGiftVcodeExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    SdkGiftVcode selectOne(SdkGiftVcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    SdkGiftVcode selectByPrimaryKey(SdkGiftVcodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGiftVcode record, @Param("example") SdkGiftVcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGiftVcode record, @Param("example") SdkGiftVcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGiftVcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift_vcode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGiftVcode record);
}