package com.cheyooh.service.sdk.db.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SdkOrderMmdoPayrepeatExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    public SdkOrderMmdoPayrepeatExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("order_no =", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("order_no <>", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("order_no >", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("order_no >=", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoLessThan(String value) {
            addCriterion("order_no <", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("order_no <=", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoLike(String value) {
            addCriterion("order_no like", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoNotLike(String value) {
            addCriterion("order_no not like", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("order_no in", values, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("order_no not in", values, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("order_no between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号
        */
        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("order_no not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIsNull() {
            addCriterion("operation_type is null");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIsNotNull() {
            addCriterion("operation_type is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeEqualTo(Integer value) {
            addCriterion("operation_type =", value, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeNotEqualTo(Integer value) {
            addCriterion("operation_type <>", value, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeGreaterThan(Integer value) {
            addCriterion("operation_type >", value, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("operation_type >=", value, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeLessThan(Integer value) {
            addCriterion("operation_type <", value, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeLessThanOrEqualTo(Integer value) {
            addCriterion("operation_type <=", value, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeIn(List<Integer> values) {
            addCriterion("operation_type in", values, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeNotIn(List<Integer> values) {
            addCriterion("operation_type not in", values, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeBetween(Integer value1, Integer value2) {
            addCriterion("operation_type between", value1, value2, "operationType");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型（1、移动，2、联通，3、电信）
        */
        public Criteria andOperationTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("operation_type not between", value1, value2, "operationType");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeIsNull() {
            addCriterion("pay_channel_code is null");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeIsNotNull() {
            addCriterion("pay_channel_code is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付通道编号
        */
        public Criteria andPayChannelCodeEqualTo(String value) {
            addCriterion("pay_channel_code =", value, "payChannelCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付通道编号
        */
        public Criteria andPayChannelCodeNotEqualTo(String value) {
            addCriterion("pay_channel_code <>", value, "payChannelCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付通道编号
        */
        public Criteria andPayChannelCodeGreaterThan(String value) {
            addCriterion("pay_channel_code >", value, "payChannelCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付通道编号
        */
        public Criteria andPayChannelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("pay_channel_code >=", value, "payChannelCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付通道编号
        */
        public Criteria andPayChannelCodeLessThan(String value) {
            addCriterion("pay_channel_code <", value, "payChannelCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付通道编号
        */
        public Criteria andPayChannelCodeLessThanOrEqualTo(String value) {
            addCriterion("pay_channel_code <=", value, "payChannelCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付通道编号
        */
        public Criteria andPayChannelCodeLike(String value) {
            addCriterion("pay_channel_code like", value, "payChannelCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付通道编号
        */
        public Criteria andPayChannelCodeNotLike(String value) {
            addCriterion("pay_channel_code not like", value, "payChannelCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付通道编号
        */
        public Criteria andPayChannelCodeIn(List<String> values) {
            addCriterion("pay_channel_code in", values, "payChannelCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付通道编号
        */
        public Criteria andPayChannelCodeNotIn(List<String> values) {
            addCriterion("pay_channel_code not in", values, "payChannelCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付通道编号
        */
        public Criteria andPayChannelCodeBetween(String value1, String value2) {
            addCriterion("pay_channel_code between", value1, value2, "payChannelCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付通道编号
        */
        public Criteria andPayChannelCodeNotBetween(String value1, String value2) {
            addCriterion("pay_channel_code not between", value1, value2, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andOriginalcodeIsNull() {
            addCriterion("originalcode is null");
            return (Criteria) this;
        }

        public Criteria andOriginalcodeIsNotNull() {
            addCriterion("originalcode is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeEqualTo(String value) {
            addCriterion("originalcode =", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeNotEqualTo(String value) {
            addCriterion("originalcode <>", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeGreaterThan(String value) {
            addCriterion("originalcode >", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeGreaterThanOrEqualTo(String value) {
            addCriterion("originalcode >=", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeLessThan(String value) {
            addCriterion("originalcode <", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeLessThanOrEqualTo(String value) {
            addCriterion("originalcode <=", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeLike(String value) {
            addCriterion("originalcode like", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeNotLike(String value) {
            addCriterion("originalcode not like", value, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeIn(List<String> values) {
            addCriterion("originalcode in", values, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeNotIn(List<String> values) {
            addCriterion("originalcode not in", values, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeBetween(String value1, String value2) {
            addCriterion("originalcode between", value1, value2, "originalcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 返回的错误原始码
        */
        public Criteria andOriginalcodeNotBetween(String value1, String value2) {
            addCriterion("originalcode not between", value1, value2, "originalcode");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion() {
            super();
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}