package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkOrderShenzhoufu;
import com.cheyooh.service.sdk.db.entity.SdkOrderShenzhoufuExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkOrderShenzhoufuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    int countByExample(SdkOrderShenzhoufuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    int deleteByExample(SdkOrderShenzhoufuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    int insert(SdkOrderShenzhoufu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    int insertSelective(SdkOrderShenzhoufu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    List<SdkOrderShenzhoufu> selectByExample(SdkOrderShenzhoufuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    Pagination<SdkOrderShenzhoufu> selectByExample(SdkOrderShenzhoufuExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    SdkOrderShenzhoufu selectOne(SdkOrderShenzhoufuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    SdkOrderShenzhoufu selectByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkOrderShenzhoufu record, @Param("example") SdkOrderShenzhoufuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkOrderShenzhoufu record, @Param("example") SdkOrderShenzhoufuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkOrderShenzhoufu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_shenzhoufu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkOrderShenzhoufu record);
}