package com.cheyooh.service.sdk.db.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SdkCmccReadIdoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    public SdkCmccReadIdoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 编号
        */
        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 编号
        */
        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 编号
        */
        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 编号
        */
        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 编号
        */
        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 编号
        */
        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 编号
        */
        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 编号
        */
        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 编号
        */
        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 编号
        */
        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 我们的订单编号
        */
        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("order_no =", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 我们的订单编号
        */
        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("order_no <>", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 我们的订单编号
        */
        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("order_no >", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 我们的订单编号
        */
        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("order_no >=", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 我们的订单编号
        */
        public Criteria andOrderNoLessThan(String value) {
            addCriterion("order_no <", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 我们的订单编号
        */
        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("order_no <=", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 我们的订单编号
        */
        public Criteria andOrderNoLike(String value) {
            addCriterion("order_no like", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 我们的订单编号
        */
        public Criteria andOrderNoNotLike(String value) {
            addCriterion("order_no not like", value, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 我们的订单编号
        */
        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("order_no in", values, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 我们的订单编号
        */
        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("order_no not in", values, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 我们的订单编号
        */
        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("order_no between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 我们的订单编号
        */
        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("order_no not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNull() {
            addCriterion("out_trade_no is null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNotNull() {
            addCriterion("out_trade_no is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: ido订单编号
        */
        public Criteria andOutTradeNoEqualTo(String value) {
            addCriterion("out_trade_no =", value, "outTradeNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: ido订单编号
        */
        public Criteria andOutTradeNoNotEqualTo(String value) {
            addCriterion("out_trade_no <>", value, "outTradeNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: ido订单编号
        */
        public Criteria andOutTradeNoGreaterThan(String value) {
            addCriterion("out_trade_no >", value, "outTradeNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: ido订单编号
        */
        public Criteria andOutTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("out_trade_no >=", value, "outTradeNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: ido订单编号
        */
        public Criteria andOutTradeNoLessThan(String value) {
            addCriterion("out_trade_no <", value, "outTradeNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: ido订单编号
        */
        public Criteria andOutTradeNoLessThanOrEqualTo(String value) {
            addCriterion("out_trade_no <=", value, "outTradeNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: ido订单编号
        */
        public Criteria andOutTradeNoLike(String value) {
            addCriterion("out_trade_no like", value, "outTradeNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: ido订单编号
        */
        public Criteria andOutTradeNoNotLike(String value) {
            addCriterion("out_trade_no not like", value, "outTradeNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: ido订单编号
        */
        public Criteria andOutTradeNoIn(List<String> values) {
            addCriterion("out_trade_no in", values, "outTradeNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: ido订单编号
        */
        public Criteria andOutTradeNoNotIn(List<String> values) {
            addCriterion("out_trade_no not in", values, "outTradeNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: ido订单编号
        */
        public Criteria andOutTradeNoBetween(String value1, String value2) {
            addCriterion("out_trade_no between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: ido订单编号
        */
        public Criteria andOutTradeNoNotBetween(String value1, String value2) {
            addCriterion("out_trade_no not between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 短信内容
        */
        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 短信内容
        */
        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 短信内容
        */
        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 短信内容
        */
        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 短信内容
        */
        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 短信内容
        */
        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 短信内容
        */
        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 短信内容
        */
        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 短信内容
        */
        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 短信内容
        */
        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 短信内容
        */
        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 短信内容
        */
        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andResultCodeIsNull() {
            addCriterion("result_code is null");
            return (Criteria) this;
        }

        public Criteria andResultCodeIsNotNull() {
            addCriterion("result_code is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 结果码, 0:失败,1:成功,2:clientHash验证失败,3:计费代码错误6:未知异常,
当结果码为非”1”数值时,其他两个参数应该为空,及时不为空也不是一个正常的订单,不能使用其进行订购操作
        */
        public Criteria andResultCodeEqualTo(String value) {
            addCriterion("result_code =", value, "resultCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 结果码, 0:失败,1:成功,2:clientHash验证失败,3:计费代码错误6:未知异常,
当结果码为非”1”数值时,其他两个参数应该为空,及时不为空也不是一个正常的订单,不能使用其进行订购操作
        */
        public Criteria andResultCodeNotEqualTo(String value) {
            addCriterion("result_code <>", value, "resultCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 结果码, 0:失败,1:成功,2:clientHash验证失败,3:计费代码错误6:未知异常,
当结果码为非”1”数值时,其他两个参数应该为空,及时不为空也不是一个正常的订单,不能使用其进行订购操作
        */
        public Criteria andResultCodeGreaterThan(String value) {
            addCriterion("result_code >", value, "resultCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 结果码, 0:失败,1:成功,2:clientHash验证失败,3:计费代码错误6:未知异常,
当结果码为非”1”数值时,其他两个参数应该为空,及时不为空也不是一个正常的订单,不能使用其进行订购操作
        */
        public Criteria andResultCodeGreaterThanOrEqualTo(String value) {
            addCriterion("result_code >=", value, "resultCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 结果码, 0:失败,1:成功,2:clientHash验证失败,3:计费代码错误6:未知异常,
当结果码为非”1”数值时,其他两个参数应该为空,及时不为空也不是一个正常的订单,不能使用其进行订购操作
        */
        public Criteria andResultCodeLessThan(String value) {
            addCriterion("result_code <", value, "resultCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 结果码, 0:失败,1:成功,2:clientHash验证失败,3:计费代码错误6:未知异常,
当结果码为非”1”数值时,其他两个参数应该为空,及时不为空也不是一个正常的订单,不能使用其进行订购操作
        */
        public Criteria andResultCodeLessThanOrEqualTo(String value) {
            addCriterion("result_code <=", value, "resultCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 结果码, 0:失败,1:成功,2:clientHash验证失败,3:计费代码错误6:未知异常,
当结果码为非”1”数值时,其他两个参数应该为空,及时不为空也不是一个正常的订单,不能使用其进行订购操作
        */
        public Criteria andResultCodeLike(String value) {
            addCriterion("result_code like", value, "resultCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 结果码, 0:失败,1:成功,2:clientHash验证失败,3:计费代码错误6:未知异常,
当结果码为非”1”数值时,其他两个参数应该为空,及时不为空也不是一个正常的订单,不能使用其进行订购操作
        */
        public Criteria andResultCodeNotLike(String value) {
            addCriterion("result_code not like", value, "resultCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 结果码, 0:失败,1:成功,2:clientHash验证失败,3:计费代码错误6:未知异常,
当结果码为非”1”数值时,其他两个参数应该为空,及时不为空也不是一个正常的订单,不能使用其进行订购操作
        */
        public Criteria andResultCodeIn(List<String> values) {
            addCriterion("result_code in", values, "resultCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 结果码, 0:失败,1:成功,2:clientHash验证失败,3:计费代码错误6:未知异常,
当结果码为非”1”数值时,其他两个参数应该为空,及时不为空也不是一个正常的订单,不能使用其进行订购操作
        */
        public Criteria andResultCodeNotIn(List<String> values) {
            addCriterion("result_code not in", values, "resultCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 结果码, 0:失败,1:成功,2:clientHash验证失败,3:计费代码错误6:未知异常,
当结果码为非”1”数值时,其他两个参数应该为空,及时不为空也不是一个正常的订单,不能使用其进行订购操作
        */
        public Criteria andResultCodeBetween(String value1, String value2) {
            addCriterion("result_code between", value1, value2, "resultCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 结果码, 0:失败,1:成功,2:clientHash验证失败,3:计费代码错误6:未知异常,
当结果码为非”1”数值时,其他两个参数应该为空,及时不为空也不是一个正常的订单,不能使用其进行订购操作
        */
        public Criteria andResultCodeNotBetween(String value1, String value2) {
            addCriterion("result_code not between", value1, value2, "resultCode");
            return (Criteria) this;
        }

        public Criteria andFeeCodeIsNull() {
            addCriterion("fee_code is null");
            return (Criteria) this;
        }

        public Criteria andFeeCodeIsNotNull() {
            addCriterion("fee_code is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费代码
        */
        public Criteria andFeeCodeEqualTo(String value) {
            addCriterion("fee_code =", value, "feeCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费代码
        */
        public Criteria andFeeCodeNotEqualTo(String value) {
            addCriterion("fee_code <>", value, "feeCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费代码
        */
        public Criteria andFeeCodeGreaterThan(String value) {
            addCriterion("fee_code >", value, "feeCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费代码
        */
        public Criteria andFeeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("fee_code >=", value, "feeCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费代码
        */
        public Criteria andFeeCodeLessThan(String value) {
            addCriterion("fee_code <", value, "feeCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费代码
        */
        public Criteria andFeeCodeLessThanOrEqualTo(String value) {
            addCriterion("fee_code <=", value, "feeCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费代码
        */
        public Criteria andFeeCodeLike(String value) {
            addCriterion("fee_code like", value, "feeCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费代码
        */
        public Criteria andFeeCodeNotLike(String value) {
            addCriterion("fee_code not like", value, "feeCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费代码
        */
        public Criteria andFeeCodeIn(List<String> values) {
            addCriterion("fee_code in", values, "feeCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费代码
        */
        public Criteria andFeeCodeNotIn(List<String> values) {
            addCriterion("fee_code not in", values, "feeCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费代码
        */
        public Criteria andFeeCodeBetween(String value1, String value2) {
            addCriterion("fee_code between", value1, value2, "feeCode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费代码
        */
        public Criteria andFeeCodeNotBetween(String value1, String value2) {
            addCriterion("fee_code not between", value1, value2, "feeCode");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费金额
        */
        public Criteria andPriceEqualTo(Float value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费金额
        */
        public Criteria andPriceNotEqualTo(Float value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费金额
        */
        public Criteria andPriceGreaterThan(Float value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费金额
        */
        public Criteria andPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费金额
        */
        public Criteria andPriceLessThan(Float value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费金额
        */
        public Criteria andPriceLessThanOrEqualTo(Float value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费金额
        */
        public Criteria andPriceIn(List<Float> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费金额
        */
        public Criteria andPriceNotIn(List<Float> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费金额
        */
        public Criteria andPriceBetween(Float value1, Float value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费金额
        */
        public Criteria andPriceNotBetween(Float value1, Float value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("updated_time is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeEqualTo(Date value) {
            addCriterion("updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeNotEqualTo(Date value) {
            addCriterion("updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeGreaterThan(Date value) {
            addCriterion("updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeLessThan(Date value) {
            addCriterion("updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeIn(List<Date> values) {
            addCriterion("updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeNotIn(List<Date> values) {
            addCriterion("updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion() {
            super();
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}