package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkUpgradeJar;
import com.cheyooh.service.sdk.db.entity.SdkUpgradeJarExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkUpgradeJarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    int countByExample(SdkUpgradeJarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    int deleteByExample(SdkUpgradeJarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    int insert(SdkUpgradeJar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    int insertSelective(SdkUpgradeJar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    List<SdkUpgradeJar> selectByExample(SdkUpgradeJarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    Pagination<SdkUpgradeJar> selectByExample(SdkUpgradeJarExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    SdkUpgradeJar selectOne(SdkUpgradeJarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    SdkUpgradeJar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkUpgradeJar record, @Param("example") SdkUpgradeJarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkUpgradeJar record, @Param("example") SdkUpgradeJarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkUpgradeJar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkUpgradeJar record);
}