package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGameWhitelist;
import com.cheyooh.service.sdk.db.entity.SdkGameWhitelistExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGameWhitelistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    int countByExample(SdkGameWhitelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGameWhitelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    int insert(SdkGameWhitelist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    int insertSelective(SdkGameWhitelist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    List<SdkGameWhitelist> selectByExample(SdkGameWhitelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    Pagination<SdkGameWhitelist> selectByExample(SdkGameWhitelistExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    SdkGameWhitelist selectOne(SdkGameWhitelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    SdkGameWhitelist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGameWhitelist record, @Param("example") SdkGameWhitelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGameWhitelist record, @Param("example") SdkGameWhitelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGameWhitelist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_whitelist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGameWhitelist record);
}