package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkNotifyOpposdk;
import com.cheyooh.service.sdk.db.entity.SdkNotifyOpposdkExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkNotifyOpposdkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    int countByExample(SdkNotifyOpposdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    int deleteByExample(SdkNotifyOpposdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    int insert(SdkNotifyOpposdk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    int insertSelective(SdkNotifyOpposdk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    List<SdkNotifyOpposdk> selectByExample(SdkNotifyOpposdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    Pagination<SdkNotifyOpposdk> selectByExample(SdkNotifyOpposdkExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    SdkNotifyOpposdk selectOne(SdkNotifyOpposdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    SdkNotifyOpposdk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkNotifyOpposdk record, @Param("example") SdkNotifyOpposdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkNotifyOpposdk record, @Param("example") SdkNotifyOpposdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkNotifyOpposdk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_opposdk
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkNotifyOpposdk record);
}