package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGamePlan;
import com.cheyooh.service.sdk.db.entity.SdkGamePlanExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGamePlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    int countByExample(SdkGamePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGamePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    int insert(SdkGamePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    int insertSelective(SdkGamePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    List<SdkGamePlan> selectByExample(SdkGamePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    Pagination<SdkGamePlan> selectByExample(SdkGamePlanExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    SdkGamePlan selectOne(SdkGamePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    SdkGamePlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGamePlan record, @Param("example") SdkGamePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGamePlan record, @Param("example") SdkGamePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGamePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGamePlan record);
}