package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkOrderWechat;
import com.cheyooh.service.sdk.db.entity.SdkOrderWechatExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkOrderWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    int countByExample(SdkOrderWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    int deleteByExample(SdkOrderWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    int insert(SdkOrderWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    int insertSelective(SdkOrderWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    List<SdkOrderWechat> selectByExample(SdkOrderWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    Pagination<SdkOrderWechat> selectByExample(SdkOrderWechatExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    SdkOrderWechat selectOne(SdkOrderWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    SdkOrderWechat selectByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkOrderWechat record, @Param("example") SdkOrderWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkOrderWechat record, @Param("example") SdkOrderWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkOrderWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wechat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkOrderWechat record);
}