package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkOrderMmdoVerifycode;
import com.cheyooh.service.sdk.db.entity.SdkOrderMmdoVerifycodeExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkOrderMmdoVerifycodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    int countByExample(SdkOrderMmdoVerifycodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    int deleteByExample(SdkOrderMmdoVerifycodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    int insert(SdkOrderMmdoVerifycode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    int insertSelective(SdkOrderMmdoVerifycode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    List<SdkOrderMmdoVerifycode> selectByExample(SdkOrderMmdoVerifycodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    Pagination<SdkOrderMmdoVerifycode> selectByExample(SdkOrderMmdoVerifycodeExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    SdkOrderMmdoVerifycode selectOne(SdkOrderMmdoVerifycodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    SdkOrderMmdoVerifycode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkOrderMmdoVerifycode record, @Param("example") SdkOrderMmdoVerifycodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkOrderMmdoVerifycode record, @Param("example") SdkOrderMmdoVerifycodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkOrderMmdoVerifycode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_verifycode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkOrderMmdoVerifycode record);
}