package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkMobileVcode;
import com.cheyooh.service.sdk.db.entity.SdkMobileVcodeExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkMobileVcodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    int countByExample(SdkMobileVcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    int deleteByExample(SdkMobileVcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    int insert(SdkMobileVcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    int insertSelective(SdkMobileVcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    List<SdkMobileVcode> selectByExample(SdkMobileVcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    Pagination<SdkMobileVcode> selectByExample(SdkMobileVcodeExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    SdkMobileVcode selectOne(SdkMobileVcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    SdkMobileVcode selectByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkMobileVcode record, @Param("example") SdkMobileVcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkMobileVcode record, @Param("example") SdkMobileVcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkMobileVcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_mobile_vcode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkMobileVcode record);
}