package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkOrderAlipay;
import com.cheyooh.service.sdk.db.entity.SdkOrderAlipayExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkOrderAlipayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    int countByExample(SdkOrderAlipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    int deleteByExample(SdkOrderAlipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    int insert(SdkOrderAlipay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    int insertSelective(SdkOrderAlipay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    List<SdkOrderAlipay> selectByExample(SdkOrderAlipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    Pagination<SdkOrderAlipay> selectByExample(SdkOrderAlipayExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    SdkOrderAlipay selectOne(SdkOrderAlipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    SdkOrderAlipay selectByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkOrderAlipay record, @Param("example") SdkOrderAlipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkOrderAlipay record, @Param("example") SdkOrderAlipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkOrderAlipay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_alipay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkOrderAlipay record);
}