package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkTelephone;
import com.cheyooh.service.sdk.db.entity.SdkTelephoneExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkTelephoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    int countByExample(SdkTelephoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    int deleteByExample(SdkTelephoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    int insert(SdkTelephone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    int insertSelective(SdkTelephone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    List<SdkTelephone> selectByExample(SdkTelephoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    Pagination<SdkTelephone> selectByExample(SdkTelephoneExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    SdkTelephone selectOne(SdkTelephoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    SdkTelephone selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkTelephone record, @Param("example") SdkTelephoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkTelephone record, @Param("example") SdkTelephoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkTelephone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkTelephone record);
}