package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkCenternumber;
import com.cheyooh.service.sdk.db.entity.SdkCenternumberExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkCenternumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    int countByExample(SdkCenternumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    int deleteByExample(SdkCenternumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    int insert(SdkCenternumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    int insertSelective(SdkCenternumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    List<SdkCenternumber> selectByExample(SdkCenternumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    Pagination<SdkCenternumber> selectByExample(SdkCenternumberExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    SdkCenternumber selectOne(SdkCenternumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    SdkCenternumber selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkCenternumber record, @Param("example") SdkCenternumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkCenternumber record, @Param("example") SdkCenternumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkCenternumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_centernumber
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkCenternumber record);
}