package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkCityAddr;
import com.cheyooh.service.sdk.db.entity.SdkCityAddrExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkCityAddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    int countByExample(SdkCityAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    int deleteByExample(SdkCityAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    int insert(SdkCityAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    int insertSelective(SdkCityAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    List<SdkCityAddr> selectByExample(SdkCityAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    Pagination<SdkCityAddr> selectByExample(SdkCityAddrExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    SdkCityAddr selectOne(SdkCityAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    SdkCityAddr selectByPrimaryKey(String provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkCityAddr record, @Param("example") SdkCityAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkCityAddr record, @Param("example") SdkCityAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkCityAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_city_addr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkCityAddr record);
}