package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGameDomainForcp;
import com.cheyooh.service.sdk.db.entity.SdkGameDomainForcpExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGameDomainForcpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    int countByExample(SdkGameDomainForcpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGameDomainForcpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    int insert(SdkGameDomainForcp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    int insertSelective(SdkGameDomainForcp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    List<SdkGameDomainForcp> selectByExample(SdkGameDomainForcpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    Pagination<SdkGameDomainForcp> selectByExample(SdkGameDomainForcpExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    SdkGameDomainForcp selectOne(SdkGameDomainForcpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    SdkGameDomainForcp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGameDomainForcp record, @Param("example") SdkGameDomainForcpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGameDomainForcp record, @Param("example") SdkGameDomainForcpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGameDomainForcp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_domain_forcp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGameDomainForcp record);
}