package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGamePayment;
import com.cheyooh.service.sdk.db.entity.SdkGamePaymentExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGamePaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    int countByExample(SdkGamePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGamePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    int insert(SdkGamePayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    int insertSelective(SdkGamePayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    List<SdkGamePayment> selectByExample(SdkGamePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    Pagination<SdkGamePayment> selectByExample(SdkGamePaymentExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    SdkGamePayment selectOne(SdkGamePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    SdkGamePayment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGamePayment record, @Param("example") SdkGamePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGamePayment record, @Param("example") SdkGamePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGamePayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGamePayment record);
}