package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGamePaysetting;
import com.cheyooh.service.sdk.db.entity.SdkGamePaysettingExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGamePaysettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    int countByExample(SdkGamePaysettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGamePaysettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    int insert(SdkGamePaysetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    int insertSelective(SdkGamePaysetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    List<SdkGamePaysetting> selectByExample(SdkGamePaysettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    Pagination<SdkGamePaysetting> selectByExample(SdkGamePaysettingExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    SdkGamePaysetting selectOne(SdkGamePaysettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    SdkGamePaysetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGamePaysetting record, @Param("example") SdkGamePaysettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGamePaysetting record, @Param("example") SdkGamePaysettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGamePaysetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_paysetting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGamePaysetting record);
}