package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGamePush;
import com.cheyooh.service.sdk.db.entity.SdkGamePushExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGamePushMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    int countByExample(SdkGamePushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGamePushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    int insert(SdkGamePush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    int insertSelective(SdkGamePush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    List<SdkGamePush> selectByExample(SdkGamePushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    Pagination<SdkGamePush> selectByExample(SdkGamePushExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    List<SdkGamePush> selectByExampleWithBLOBs(SdkGamePushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    Pagination<SdkGamePush> selectByExampleWithBLOBs(SdkGamePushExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    SdkGamePush selectOne(SdkGamePushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    SdkGamePush selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGamePush record, @Param("example") SdkGamePushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SdkGamePush record, @Param("example") SdkGamePushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGamePush record, @Param("example") SdkGamePushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGamePush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SdkGamePush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_push
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGamePush record);
}