package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGameBlacklist;
import com.cheyooh.service.sdk.db.entity.SdkGameBlacklistExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGameBlacklistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    int countByExample(SdkGameBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGameBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    int insert(SdkGameBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    int insertSelective(SdkGameBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    List<SdkGameBlacklist> selectByExample(SdkGameBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    Pagination<SdkGameBlacklist> selectByExample(SdkGameBlacklistExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    SdkGameBlacklist selectOne(SdkGameBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    SdkGameBlacklist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGameBlacklist record, @Param("example") SdkGameBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGameBlacklist record, @Param("example") SdkGameBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGameBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_blacklist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGameBlacklist record);
}