package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGift;
import com.cheyooh.service.sdk.db.entity.SdkGiftExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    int countByExample(SdkGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer giftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    int insert(SdkGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    int insertSelective(SdkGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    List<SdkGift> selectByExample(SdkGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    Pagination<SdkGift> selectByExample(SdkGiftExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    List<SdkGift> selectByExampleWithBLOBs(SdkGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    Pagination<SdkGift> selectByExampleWithBLOBs(SdkGiftExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    SdkGift selectOne(SdkGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    SdkGift selectByPrimaryKey(Integer giftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGift record, @Param("example") SdkGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SdkGift record, @Param("example") SdkGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGift record, @Param("example") SdkGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SdkGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_gift
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGift record);
}