package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkNotifySinaMonthly;
import com.cheyooh.service.sdk.db.entity.SdkNotifySinaMonthlyExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkNotifySinaMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    int countByExample(SdkNotifySinaMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    int deleteByExample(SdkNotifySinaMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    int insert(SdkNotifySinaMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    int insertSelective(SdkNotifySinaMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    List<SdkNotifySinaMonthly> selectByExample(SdkNotifySinaMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    Pagination<SdkNotifySinaMonthly> selectByExample(SdkNotifySinaMonthlyExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    SdkNotifySinaMonthly selectOne(SdkNotifySinaMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    SdkNotifySinaMonthly selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkNotifySinaMonthly record, @Param("example") SdkNotifySinaMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkNotifySinaMonthly record, @Param("example") SdkNotifySinaMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkNotifySinaMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_sina_monthly
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkNotifySinaMonthly record);
}