package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkNotifyUcsasdk;
import com.cheyooh.service.sdk.db.entity.SdkNotifyUcsasdkExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkNotifyUcsasdkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    int countByExample(SdkNotifyUcsasdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    int deleteByExample(SdkNotifyUcsasdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    int insert(SdkNotifyUcsasdk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    int insertSelective(SdkNotifyUcsasdk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    List<SdkNotifyUcsasdk> selectByExample(SdkNotifyUcsasdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    Pagination<SdkNotifyUcsasdk> selectByExample(SdkNotifyUcsasdkExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    SdkNotifyUcsasdk selectOne(SdkNotifyUcsasdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    SdkNotifyUcsasdk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkNotifyUcsasdk record, @Param("example") SdkNotifyUcsasdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkNotifyUcsasdk record, @Param("example") SdkNotifyUcsasdkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkNotifyUcsasdk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_notify_ucsasdk
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkNotifyUcsasdk record);
}