package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkOrderMmdoPayrepeat;
import com.cheyooh.service.sdk.db.entity.SdkOrderMmdoPayrepeatExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkOrderMmdoPayrepeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    int countByExample(SdkOrderMmdoPayrepeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    int deleteByExample(SdkOrderMmdoPayrepeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    int insert(SdkOrderMmdoPayrepeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    int insertSelective(SdkOrderMmdoPayrepeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    List<SdkOrderMmdoPayrepeat> selectByExample(SdkOrderMmdoPayrepeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    Pagination<SdkOrderMmdoPayrepeat> selectByExample(SdkOrderMmdoPayrepeatExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    SdkOrderMmdoPayrepeat selectOne(SdkOrderMmdoPayrepeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    SdkOrderMmdoPayrepeat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkOrderMmdoPayrepeat record, @Param("example") SdkOrderMmdoPayrepeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkOrderMmdoPayrepeat record, @Param("example") SdkOrderMmdoPayrepeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkOrderMmdoPayrepeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo_payrepeat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkOrderMmdoPayrepeat record);
}