package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkOrderWiipay;
import com.cheyooh.service.sdk.db.entity.SdkOrderWiipayExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkOrderWiipayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    int countByExample(SdkOrderWiipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    int deleteByExample(SdkOrderWiipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    int insert(SdkOrderWiipay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    int insertSelective(SdkOrderWiipay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    List<SdkOrderWiipay> selectByExample(SdkOrderWiipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    Pagination<SdkOrderWiipay> selectByExample(SdkOrderWiipayExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    SdkOrderWiipay selectOne(SdkOrderWiipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    SdkOrderWiipay selectByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkOrderWiipay record, @Param("example") SdkOrderWiipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkOrderWiipay record, @Param("example") SdkOrderWiipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkOrderWiipay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkOrderWiipay record);
}