package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkOperatorPayLimit;
import com.cheyooh.service.sdk.db.entity.SdkOperatorPayLimitExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkOperatorPayLimitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    int countByExample(SdkOperatorPayLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    int deleteByExample(SdkOperatorPayLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    int insert(SdkOperatorPayLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    int insertSelective(SdkOperatorPayLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    List<SdkOperatorPayLimit> selectByExample(SdkOperatorPayLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    Pagination<SdkOperatorPayLimit> selectByExample(SdkOperatorPayLimitExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    SdkOperatorPayLimit selectOne(SdkOperatorPayLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    SdkOperatorPayLimit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkOperatorPayLimit record, @Param("example") SdkOperatorPayLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkOperatorPayLimit record, @Param("example") SdkOperatorPayLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkOperatorPayLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_limit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkOperatorPayLimit record);
}