package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkPropsSetting;
import com.cheyooh.service.sdk.db.entity.SdkPropsSettingExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkPropsSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    int countByExample(SdkPropsSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    int deleteByExample(SdkPropsSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    int insert(SdkPropsSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    int insertSelective(SdkPropsSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    List<SdkPropsSetting> selectByExample(SdkPropsSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    Pagination<SdkPropsSetting> selectByExample(SdkPropsSettingExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    SdkPropsSetting selectOne(SdkPropsSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    SdkPropsSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkPropsSetting record, @Param("example") SdkPropsSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkPropsSetting record, @Param("example") SdkPropsSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkPropsSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkPropsSetting record);
}