package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkProvinceAddr;
import com.cheyooh.service.sdk.db.entity.SdkProvinceAddrExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkProvinceAddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    int countByExample(SdkProvinceAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    int deleteByExample(SdkProvinceAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    int insert(SdkProvinceAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    int insertSelective(SdkProvinceAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    List<SdkProvinceAddr> selectByExample(SdkProvinceAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    Pagination<SdkProvinceAddr> selectByExample(SdkProvinceAddrExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    SdkProvinceAddr selectOne(SdkProvinceAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    SdkProvinceAddr selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkProvinceAddr record, @Param("example") SdkProvinceAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkProvinceAddr record, @Param("example") SdkProvinceAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkProvinceAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_province_addr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkProvinceAddr record);
}