package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkSmsGame;
import com.cheyooh.service.sdk.db.entity.SdkSmsGameExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkSmsGameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    int countByExample(SdkSmsGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    int deleteByExample(SdkSmsGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    int insert(SdkSmsGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    int insertSelective(SdkSmsGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    List<SdkSmsGame> selectByExample(SdkSmsGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    Pagination<SdkSmsGame> selectByExample(SdkSmsGameExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    SdkSmsGame selectOne(SdkSmsGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    SdkSmsGame selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkSmsGame record, @Param("example") SdkSmsGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkSmsGame record, @Param("example") SdkSmsGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkSmsGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms_game
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkSmsGame record);
}