package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkSwbInfo;
import com.cheyooh.service.sdk.db.entity.SdkSwbInfoExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkSwbInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    int countByExample(SdkSwbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    int deleteByExample(SdkSwbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    int insert(SdkSwbInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    int insertSelective(SdkSwbInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    List<SdkSwbInfo> selectByExample(SdkSwbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    Pagination<SdkSwbInfo> selectByExample(SdkSwbInfoExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    SdkSwbInfo selectOne(SdkSwbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    SdkSwbInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkSwbInfo record, @Param("example") SdkSwbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkSwbInfo record, @Param("example") SdkSwbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkSwbInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_swb_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkSwbInfo record);
}