package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkTelephoneCenternumber;
import com.cheyooh.service.sdk.db.entity.SdkTelephoneCenternumberExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkTelephoneCenternumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    int countByExample(SdkTelephoneCenternumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    int deleteByExample(SdkTelephoneCenternumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    int insert(SdkTelephoneCenternumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    int insertSelective(SdkTelephoneCenternumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    List<SdkTelephoneCenternumber> selectByExample(SdkTelephoneCenternumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    Pagination<SdkTelephoneCenternumber> selectByExample(SdkTelephoneCenternumberExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    SdkTelephoneCenternumber selectOne(SdkTelephoneCenternumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    SdkTelephoneCenternumber selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkTelephoneCenternumber record, @Param("example") SdkTelephoneCenternumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkTelephoneCenternumber record, @Param("example") SdkTelephoneCenternumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkTelephoneCenternumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_telephone_centernumber
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkTelephoneCenternumber record);
}