package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkUpgradeJarGame;
import com.cheyooh.service.sdk.db.entity.SdkUpgradeJarGameExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkUpgradeJarGameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    int countByExample(SdkUpgradeJarGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    int deleteByExample(SdkUpgradeJarGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    int insert(SdkUpgradeJarGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    int insertSelective(SdkUpgradeJarGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    List<SdkUpgradeJarGame> selectByExample(SdkUpgradeJarGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    Pagination<SdkUpgradeJarGame> selectByExample(SdkUpgradeJarGameExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    SdkUpgradeJarGame selectOne(SdkUpgradeJarGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    SdkUpgradeJarGame selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkUpgradeJarGame record, @Param("example") SdkUpgradeJarGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkUpgradeJarGame record, @Param("example") SdkUpgradeJarGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkUpgradeJarGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_upgrade_jar_game
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkUpgradeJarGame record);
}