package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkCmccReadIdo;
import com.cheyooh.service.sdk.db.entity.SdkCmccReadIdoExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkCmccReadIdoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    int countByExample(SdkCmccReadIdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    int deleteByExample(SdkCmccReadIdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    int insert(SdkCmccReadIdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    int insertSelective(SdkCmccReadIdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    List<SdkCmccReadIdo> selectByExample(SdkCmccReadIdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    Pagination<SdkCmccReadIdo> selectByExample(SdkCmccReadIdoExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    SdkCmccReadIdo selectOne(SdkCmccReadIdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    SdkCmccReadIdo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkCmccReadIdo record, @Param("example") SdkCmccReadIdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkCmccReadIdo record, @Param("example") SdkCmccReadIdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkCmccReadIdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_cmcc_read_ido
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkCmccReadIdo record);
}