package com.cheyooh.service.sdk.db.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SdkOrderWiipayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    public SdkOrderWiipayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPayIdIsNull() {
            addCriterion("pay_id is null");
            return (Criteria) this;
        }

        public Criteria andPayIdIsNotNull() {
            addCriterion("pay_id is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andPayIdEqualTo(Integer value) {
            addCriterion("pay_id =", value, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andPayIdNotEqualTo(Integer value) {
            addCriterion("pay_id <>", value, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andPayIdGreaterThan(Integer value) {
            addCriterion("pay_id >", value, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andPayIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_id >=", value, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andPayIdLessThan(Integer value) {
            addCriterion("pay_id <", value, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andPayIdLessThanOrEqualTo(Integer value) {
            addCriterion("pay_id <=", value, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andPayIdIn(List<Integer> values) {
            addCriterion("pay_id in", values, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andPayIdNotIn(List<Integer> values) {
            addCriterion("pay_id not in", values, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andPayIdBetween(Integer value1, Integer value2) {
            addCriterion("pay_id between", value1, value2, "payId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andPayIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_id not between", value1, value2, "payId");
            return (Criteria) this;
        }

        public Criteria andReqTimeIsNull() {
            addCriterion("req_time is null");
            return (Criteria) this;
        }

        public Criteria andReqTimeIsNotNull() {
            addCriterion("req_time is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求时间
        */
        public Criteria andReqTimeEqualTo(Date value) {
            addCriterion("req_time =", value, "reqTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求时间
        */
        public Criteria andReqTimeNotEqualTo(Date value) {
            addCriterion("req_time <>", value, "reqTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求时间
        */
        public Criteria andReqTimeGreaterThan(Date value) {
            addCriterion("req_time >", value, "reqTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求时间
        */
        public Criteria andReqTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("req_time >=", value, "reqTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求时间
        */
        public Criteria andReqTimeLessThan(Date value) {
            addCriterion("req_time <", value, "reqTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求时间
        */
        public Criteria andReqTimeLessThanOrEqualTo(Date value) {
            addCriterion("req_time <=", value, "reqTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求时间
        */
        public Criteria andReqTimeIn(List<Date> values) {
            addCriterion("req_time in", values, "reqTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求时间
        */
        public Criteria andReqTimeNotIn(List<Date> values) {
            addCriterion("req_time not in", values, "reqTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求时间
        */
        public Criteria andReqTimeBetween(Date value1, Date value2) {
            addCriterion("req_time between", value1, value2, "reqTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 请求时间
        */
        public Criteria andReqTimeNotBetween(Date value1, Date value2) {
            addCriterion("req_time not between", value1, value2, "reqTime");
            return (Criteria) this;
        }

        public Criteria andReqOrderIsNull() {
            addCriterion("req_Order is null");
            return (Criteria) this;
        }

        public Criteria andReqOrderIsNotNull() {
            addCriterion("req_Order is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 商户订单号,提交的订单号必须在自身账户交易中唯一
        */
        public Criteria andReqOrderEqualTo(String value) {
            addCriterion("req_Order =", value, "reqOrder");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 商户订单号,提交的订单号必须在自身账户交易中唯一
        */
        public Criteria andReqOrderNotEqualTo(String value) {
            addCriterion("req_Order <>", value, "reqOrder");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 商户订单号,提交的订单号必须在自身账户交易中唯一
        */
        public Criteria andReqOrderGreaterThan(String value) {
            addCriterion("req_Order >", value, "reqOrder");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 商户订单号,提交的订单号必须在自身账户交易中唯一
        */
        public Criteria andReqOrderGreaterThanOrEqualTo(String value) {
            addCriterion("req_Order >=", value, "reqOrder");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 商户订单号,提交的订单号必须在自身账户交易中唯一
        */
        public Criteria andReqOrderLessThan(String value) {
            addCriterion("req_Order <", value, "reqOrder");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 商户订单号,提交的订单号必须在自身账户交易中唯一
        */
        public Criteria andReqOrderLessThanOrEqualTo(String value) {
            addCriterion("req_Order <=", value, "reqOrder");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 商户订单号,提交的订单号必须在自身账户交易中唯一
        */
        public Criteria andReqOrderLike(String value) {
            addCriterion("req_Order like", value, "reqOrder");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 商户订单号,提交的订单号必须在自身账户交易中唯一
        */
        public Criteria andReqOrderNotLike(String value) {
            addCriterion("req_Order not like", value, "reqOrder");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 商户订单号,提交的订单号必须在自身账户交易中唯一
        */
        public Criteria andReqOrderIn(List<String> values) {
            addCriterion("req_Order in", values, "reqOrder");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 商户订单号,提交的订单号必须在自身账户交易中唯一
        */
        public Criteria andReqOrderNotIn(List<String> values) {
            addCriterion("req_Order not in", values, "reqOrder");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 商户订单号,提交的订单号必须在自身账户交易中唯一
        */
        public Criteria andReqOrderBetween(String value1, String value2) {
            addCriterion("req_Order between", value1, value2, "reqOrder");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 商户订单号,提交的订单号必须在自身账户交易中唯一
        */
        public Criteria andReqOrderNotBetween(String value1, String value2) {
            addCriterion("req_Order not between", value1, value2, "reqOrder");
            return (Criteria) this;
        }

        public Criteria andReqAmtIsNull() {
            addCriterion("req_Amt is null");
            return (Criteria) this;
        }

        public Criteria andReqAmtIsNotNull() {
            addCriterion("req_Amt is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付金额 , 单位:元，精确到分. 
        */
        public Criteria andReqAmtEqualTo(Float value) {
            addCriterion("req_Amt =", value, "reqAmt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付金额 , 单位:元，精确到分. 
        */
        public Criteria andReqAmtNotEqualTo(Float value) {
            addCriterion("req_Amt <>", value, "reqAmt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付金额 , 单位:元，精确到分. 
        */
        public Criteria andReqAmtGreaterThan(Float value) {
            addCriterion("req_Amt >", value, "reqAmt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付金额 , 单位:元，精确到分. 
        */
        public Criteria andReqAmtGreaterThanOrEqualTo(Float value) {
            addCriterion("req_Amt >=", value, "reqAmt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付金额 , 单位:元，精确到分. 
        */
        public Criteria andReqAmtLessThan(Float value) {
            addCriterion("req_Amt <", value, "reqAmt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付金额 , 单位:元，精确到分. 
        */
        public Criteria andReqAmtLessThanOrEqualTo(Float value) {
            addCriterion("req_Amt <=", value, "reqAmt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付金额 , 单位:元，精确到分. 
        */
        public Criteria andReqAmtIn(List<Float> values) {
            addCriterion("req_Amt in", values, "reqAmt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付金额 , 单位:元，精确到分. 
        */
        public Criteria andReqAmtNotIn(List<Float> values) {
            addCriterion("req_Amt not in", values, "reqAmt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付金额 , 单位:元，精确到分. 
        */
        public Criteria andReqAmtBetween(Float value1, Float value2) {
            addCriterion("req_Amt between", value1, value2, "reqAmt");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付金额 , 单位:元，精确到分. 
        */
        public Criteria andReqAmtNotBetween(Float value1, Float value2) {
            addCriterion("req_Amt not between", value1, value2, "reqAmt");
            return (Criteria) this;
        }

        public Criteria andReqPaycodeIsNull() {
            addCriterion("req_payCode is null");
            return (Criteria) this;
        }

        public Criteria andReqPaycodeIsNotNull() {
            addCriterion("req_payCode is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andReqPaycodeEqualTo(String value) {
            addCriterion("req_payCode =", value, "reqPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andReqPaycodeNotEqualTo(String value) {
            addCriterion("req_payCode <>", value, "reqPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andReqPaycodeGreaterThan(String value) {
            addCriterion("req_payCode >", value, "reqPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andReqPaycodeGreaterThanOrEqualTo(String value) {
            addCriterion("req_payCode >=", value, "reqPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andReqPaycodeLessThan(String value) {
            addCriterion("req_payCode <", value, "reqPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andReqPaycodeLessThanOrEqualTo(String value) {
            addCriterion("req_payCode <=", value, "reqPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andReqPaycodeLike(String value) {
            addCriterion("req_payCode like", value, "reqPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andReqPaycodeNotLike(String value) {
            addCriterion("req_payCode not like", value, "reqPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andReqPaycodeIn(List<String> values) {
            addCriterion("req_payCode in", values, "reqPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andReqPaycodeNotIn(List<String> values) {
            addCriterion("req_payCode not in", values, "reqPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andReqPaycodeBetween(String value1, String value2) {
            addCriterion("req_payCode between", value1, value2, "reqPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andReqPaycodeNotBetween(String value1, String value2) {
            addCriterion("req_payCode not between", value1, value2, "reqPaycode");
            return (Criteria) this;
        }

        public Criteria andNotifyDateIsNull() {
            addCriterion("notify_date is null");
            return (Criteria) this;
        }

        public Criteria andNotifyDateIsNotNull() {
            addCriterion("notify_date is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 通知时间
        */
        public Criteria andNotifyDateEqualTo(Date value) {
            addCriterion("notify_date =", value, "notifyDate");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 通知时间
        */
        public Criteria andNotifyDateNotEqualTo(Date value) {
            addCriterion("notify_date <>", value, "notifyDate");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 通知时间
        */
        public Criteria andNotifyDateGreaterThan(Date value) {
            addCriterion("notify_date >", value, "notifyDate");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 通知时间
        */
        public Criteria andNotifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("notify_date >=", value, "notifyDate");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 通知时间
        */
        public Criteria andNotifyDateLessThan(Date value) {
            addCriterion("notify_date <", value, "notifyDate");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 通知时间
        */
        public Criteria andNotifyDateLessThanOrEqualTo(Date value) {
            addCriterion("notify_date <=", value, "notifyDate");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 通知时间
        */
        public Criteria andNotifyDateIn(List<Date> values) {
            addCriterion("notify_date in", values, "notifyDate");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 通知时间
        */
        public Criteria andNotifyDateNotIn(List<Date> values) {
            addCriterion("notify_date not in", values, "notifyDate");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 通知时间
        */
        public Criteria andNotifyDateBetween(Date value1, Date value2) {
            addCriterion("notify_date between", value1, value2, "notifyDate");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 通知时间
        */
        public Criteria andNotifyDateNotBetween(Date value1, Date value2) {
            addCriterion("notify_date not between", value1, value2, "notifyDate");
            return (Criteria) this;
        }

        public Criteria andNotifyOperatortypeIsNull() {
            addCriterion("notify_operatorType is null");
            return (Criteria) this;
        }

        public Criteria andNotifyOperatortypeIsNotNull() {
            addCriterion("notify_operatorType is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型
        */
        public Criteria andNotifyOperatortypeEqualTo(String value) {
            addCriterion("notify_operatorType =", value, "notifyOperatortype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型
        */
        public Criteria andNotifyOperatortypeNotEqualTo(String value) {
            addCriterion("notify_operatorType <>", value, "notifyOperatortype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型
        */
        public Criteria andNotifyOperatortypeGreaterThan(String value) {
            addCriterion("notify_operatorType >", value, "notifyOperatortype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型
        */
        public Criteria andNotifyOperatortypeGreaterThanOrEqualTo(String value) {
            addCriterion("notify_operatorType >=", value, "notifyOperatortype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型
        */
        public Criteria andNotifyOperatortypeLessThan(String value) {
            addCriterion("notify_operatorType <", value, "notifyOperatortype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型
        */
        public Criteria andNotifyOperatortypeLessThanOrEqualTo(String value) {
            addCriterion("notify_operatorType <=", value, "notifyOperatortype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型
        */
        public Criteria andNotifyOperatortypeLike(String value) {
            addCriterion("notify_operatorType like", value, "notifyOperatortype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型
        */
        public Criteria andNotifyOperatortypeNotLike(String value) {
            addCriterion("notify_operatorType not like", value, "notifyOperatortype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型
        */
        public Criteria andNotifyOperatortypeIn(List<String> values) {
            addCriterion("notify_operatorType in", values, "notifyOperatortype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型
        */
        public Criteria andNotifyOperatortypeNotIn(List<String> values) {
            addCriterion("notify_operatorType not in", values, "notifyOperatortype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型
        */
        public Criteria andNotifyOperatortypeBetween(String value1, String value2) {
            addCriterion("notify_operatorType between", value1, value2, "notifyOperatortype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商类型
        */
        public Criteria andNotifyOperatortypeNotBetween(String value1, String value2) {
            addCriterion("notify_operatorType not between", value1, value2, "notifyOperatortype");
            return (Criteria) this;
        }

        public Criteria andNotifyOperatortypetileIsNull() {
            addCriterion("notify_operatorTypeTile is null");
            return (Criteria) this;
        }

        public Criteria andNotifyOperatortypetileIsNotNull() {
            addCriterion("notify_operatorTypeTile is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商名
        */
        public Criteria andNotifyOperatortypetileEqualTo(String value) {
            addCriterion("notify_operatorTypeTile =", value, "notifyOperatortypetile");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商名
        */
        public Criteria andNotifyOperatortypetileNotEqualTo(String value) {
            addCriterion("notify_operatorTypeTile <>", value, "notifyOperatortypetile");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商名
        */
        public Criteria andNotifyOperatortypetileGreaterThan(String value) {
            addCriterion("notify_operatorTypeTile >", value, "notifyOperatortypetile");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商名
        */
        public Criteria andNotifyOperatortypetileGreaterThanOrEqualTo(String value) {
            addCriterion("notify_operatorTypeTile >=", value, "notifyOperatortypetile");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商名
        */
        public Criteria andNotifyOperatortypetileLessThan(String value) {
            addCriterion("notify_operatorTypeTile <", value, "notifyOperatortypetile");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商名
        */
        public Criteria andNotifyOperatortypetileLessThanOrEqualTo(String value) {
            addCriterion("notify_operatorTypeTile <=", value, "notifyOperatortypetile");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商名
        */
        public Criteria andNotifyOperatortypetileLike(String value) {
            addCriterion("notify_operatorTypeTile like", value, "notifyOperatortypetile");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商名
        */
        public Criteria andNotifyOperatortypetileNotLike(String value) {
            addCriterion("notify_operatorTypeTile not like", value, "notifyOperatortypetile");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商名
        */
        public Criteria andNotifyOperatortypetileIn(List<String> values) {
            addCriterion("notify_operatorTypeTile in", values, "notifyOperatortypetile");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商名
        */
        public Criteria andNotifyOperatortypetileNotIn(List<String> values) {
            addCriterion("notify_operatorTypeTile not in", values, "notifyOperatortypetile");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商名
        */
        public Criteria andNotifyOperatortypetileBetween(String value1, String value2) {
            addCriterion("notify_operatorTypeTile between", value1, value2, "notifyOperatortypetile");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商名
        */
        public Criteria andNotifyOperatortypetileNotBetween(String value1, String value2) {
            addCriterion("notify_operatorTypeTile not between", value1, value2, "notifyOperatortypetile");
            return (Criteria) this;
        }

        public Criteria andNotifyChannelcodeIsNull() {
            addCriterion("notify_channelCode is null");
            return (Criteria) this;
        }

        public Criteria andNotifyChannelcodeIsNotNull() {
            addCriterion("notify_channelCode is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andNotifyChannelcodeEqualTo(String value) {
            addCriterion("notify_channelCode =", value, "notifyChannelcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andNotifyChannelcodeNotEqualTo(String value) {
            addCriterion("notify_channelCode <>", value, "notifyChannelcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andNotifyChannelcodeGreaterThan(String value) {
            addCriterion("notify_channelCode >", value, "notifyChannelcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andNotifyChannelcodeGreaterThanOrEqualTo(String value) {
            addCriterion("notify_channelCode >=", value, "notifyChannelcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andNotifyChannelcodeLessThan(String value) {
            addCriterion("notify_channelCode <", value, "notifyChannelcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andNotifyChannelcodeLessThanOrEqualTo(String value) {
            addCriterion("notify_channelCode <=", value, "notifyChannelcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andNotifyChannelcodeLike(String value) {
            addCriterion("notify_channelCode like", value, "notifyChannelcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andNotifyChannelcodeNotLike(String value) {
            addCriterion("notify_channelCode not like", value, "notifyChannelcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andNotifyChannelcodeIn(List<String> values) {
            addCriterion("notify_channelCode in", values, "notifyChannelcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andNotifyChannelcodeNotIn(List<String> values) {
            addCriterion("notify_channelCode not in", values, "notifyChannelcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andNotifyChannelcodeBetween(String value1, String value2) {
            addCriterion("notify_channelCode between", value1, value2, "notifyChannelcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 渠道号
        */
        public Criteria andNotifyChannelcodeNotBetween(String value1, String value2) {
            addCriterion("notify_channelCode not between", value1, value2, "notifyChannelcode");
            return (Criteria) this;
        }

        public Criteria andNotifyAppcodeIsNull() {
            addCriterion("notify_appCode is null");
            return (Criteria) this;
        }

        public Criteria andNotifyAppcodeIsNotNull() {
            addCriterion("notify_appCode is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 应用编号
        */
        public Criteria andNotifyAppcodeEqualTo(String value) {
            addCriterion("notify_appCode =", value, "notifyAppcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 应用编号
        */
        public Criteria andNotifyAppcodeNotEqualTo(String value) {
            addCriterion("notify_appCode <>", value, "notifyAppcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 应用编号
        */
        public Criteria andNotifyAppcodeGreaterThan(String value) {
            addCriterion("notify_appCode >", value, "notifyAppcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 应用编号
        */
        public Criteria andNotifyAppcodeGreaterThanOrEqualTo(String value) {
            addCriterion("notify_appCode >=", value, "notifyAppcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 应用编号
        */
        public Criteria andNotifyAppcodeLessThan(String value) {
            addCriterion("notify_appCode <", value, "notifyAppcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 应用编号
        */
        public Criteria andNotifyAppcodeLessThanOrEqualTo(String value) {
            addCriterion("notify_appCode <=", value, "notifyAppcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 应用编号
        */
        public Criteria andNotifyAppcodeLike(String value) {
            addCriterion("notify_appCode like", value, "notifyAppcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 应用编号
        */
        public Criteria andNotifyAppcodeNotLike(String value) {
            addCriterion("notify_appCode not like", value, "notifyAppcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 应用编号
        */
        public Criteria andNotifyAppcodeIn(List<String> values) {
            addCriterion("notify_appCode in", values, "notifyAppcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 应用编号
        */
        public Criteria andNotifyAppcodeNotIn(List<String> values) {
            addCriterion("notify_appCode not in", values, "notifyAppcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 应用编号
        */
        public Criteria andNotifyAppcodeBetween(String value1, String value2) {
            addCriterion("notify_appCode between", value1, value2, "notifyAppcode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 应用编号
        */
        public Criteria andNotifyAppcodeNotBetween(String value1, String value2) {
            addCriterion("notify_appCode not between", value1, value2, "notifyAppcode");
            return (Criteria) this;
        }

        public Criteria andNotifyPaycodeIsNull() {
            addCriterion("notify_payCode is null");
            return (Criteria) this;
        }

        public Criteria andNotifyPaycodeIsNotNull() {
            addCriterion("notify_payCode is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andNotifyPaycodeEqualTo(String value) {
            addCriterion("notify_payCode =", value, "notifyPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andNotifyPaycodeNotEqualTo(String value) {
            addCriterion("notify_payCode <>", value, "notifyPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andNotifyPaycodeGreaterThan(String value) {
            addCriterion("notify_payCode >", value, "notifyPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andNotifyPaycodeGreaterThanOrEqualTo(String value) {
            addCriterion("notify_payCode >=", value, "notifyPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andNotifyPaycodeLessThan(String value) {
            addCriterion("notify_payCode <", value, "notifyPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andNotifyPaycodeLessThanOrEqualTo(String value) {
            addCriterion("notify_payCode <=", value, "notifyPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andNotifyPaycodeLike(String value) {
            addCriterion("notify_payCode like", value, "notifyPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andNotifyPaycodeNotLike(String value) {
            addCriterion("notify_payCode not like", value, "notifyPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andNotifyPaycodeIn(List<String> values) {
            addCriterion("notify_payCode in", values, "notifyPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andNotifyPaycodeNotIn(List<String> values) {
            addCriterion("notify_payCode not in", values, "notifyPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andNotifyPaycodeBetween(String value1, String value2) {
            addCriterion("notify_payCode between", value1, value2, "notifyPaycode");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 计费编号
        */
        public Criteria andNotifyPaycodeNotBetween(String value1, String value2) {
            addCriterion("notify_payCode not between", value1, value2, "notifyPaycode");
            return (Criteria) this;
        }

        public Criteria andNotifyImsiIsNull() {
            addCriterion("notify_imsi is null");
            return (Criteria) this;
        }

        public Criteria andNotifyImsiIsNotNull() {
            addCriterion("notify_imsi is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机卡imsi
        */
        public Criteria andNotifyImsiEqualTo(String value) {
            addCriterion("notify_imsi =", value, "notifyImsi");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机卡imsi
        */
        public Criteria andNotifyImsiNotEqualTo(String value) {
            addCriterion("notify_imsi <>", value, "notifyImsi");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机卡imsi
        */
        public Criteria andNotifyImsiGreaterThan(String value) {
            addCriterion("notify_imsi >", value, "notifyImsi");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机卡imsi
        */
        public Criteria andNotifyImsiGreaterThanOrEqualTo(String value) {
            addCriterion("notify_imsi >=", value, "notifyImsi");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机卡imsi
        */
        public Criteria andNotifyImsiLessThan(String value) {
            addCriterion("notify_imsi <", value, "notifyImsi");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机卡imsi
        */
        public Criteria andNotifyImsiLessThanOrEqualTo(String value) {
            addCriterion("notify_imsi <=", value, "notifyImsi");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机卡imsi
        */
        public Criteria andNotifyImsiLike(String value) {
            addCriterion("notify_imsi like", value, "notifyImsi");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机卡imsi
        */
        public Criteria andNotifyImsiNotLike(String value) {
            addCriterion("notify_imsi not like", value, "notifyImsi");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机卡imsi
        */
        public Criteria andNotifyImsiIn(List<String> values) {
            addCriterion("notify_imsi in", values, "notifyImsi");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机卡imsi
        */
        public Criteria andNotifyImsiNotIn(List<String> values) {
            addCriterion("notify_imsi not in", values, "notifyImsi");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机卡imsi
        */
        public Criteria andNotifyImsiBetween(String value1, String value2) {
            addCriterion("notify_imsi between", value1, value2, "notifyImsi");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机卡imsi
        */
        public Criteria andNotifyImsiNotBetween(String value1, String value2) {
            addCriterion("notify_imsi not between", value1, value2, "notifyImsi");
            return (Criteria) this;
        }

        public Criteria andNotifyTelIsNull() {
            addCriterion("notify_tel is null");
            return (Criteria) this;
        }

        public Criteria andNotifyTelIsNotNull() {
            addCriterion("notify_tel is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号
        */
        public Criteria andNotifyTelEqualTo(String value) {
            addCriterion("notify_tel =", value, "notifyTel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号
        */
        public Criteria andNotifyTelNotEqualTo(String value) {
            addCriterion("notify_tel <>", value, "notifyTel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号
        */
        public Criteria andNotifyTelGreaterThan(String value) {
            addCriterion("notify_tel >", value, "notifyTel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号
        */
        public Criteria andNotifyTelGreaterThanOrEqualTo(String value) {
            addCriterion("notify_tel >=", value, "notifyTel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号
        */
        public Criteria andNotifyTelLessThan(String value) {
            addCriterion("notify_tel <", value, "notifyTel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号
        */
        public Criteria andNotifyTelLessThanOrEqualTo(String value) {
            addCriterion("notify_tel <=", value, "notifyTel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号
        */
        public Criteria andNotifyTelLike(String value) {
            addCriterion("notify_tel like", value, "notifyTel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号
        */
        public Criteria andNotifyTelNotLike(String value) {
            addCriterion("notify_tel not like", value, "notifyTel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号
        */
        public Criteria andNotifyTelIn(List<String> values) {
            addCriterion("notify_tel in", values, "notifyTel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号
        */
        public Criteria andNotifyTelNotIn(List<String> values) {
            addCriterion("notify_tel not in", values, "notifyTel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号
        */
        public Criteria andNotifyTelBetween(String value1, String value2) {
            addCriterion("notify_tel between", value1, value2, "notifyTel");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 手机号
        */
        public Criteria andNotifyTelNotBetween(String value1, String value2) {
            addCriterion("notify_tel not between", value1, value2, "notifyTel");
            return (Criteria) this;
        }

        public Criteria andNotifyStateIsNull() {
            addCriterion("notify_state is null");
            return (Criteria) this;
        }

        public Criteria andNotifyStateIsNotNull() {
            addCriterion("notify_state is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: success表示成功，其他一切表示失败
        */
        public Criteria andNotifyStateEqualTo(String value) {
            addCriterion("notify_state =", value, "notifyState");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: success表示成功，其他一切表示失败
        */
        public Criteria andNotifyStateNotEqualTo(String value) {
            addCriterion("notify_state <>", value, "notifyState");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: success表示成功，其他一切表示失败
        */
        public Criteria andNotifyStateGreaterThan(String value) {
            addCriterion("notify_state >", value, "notifyState");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: success表示成功，其他一切表示失败
        */
        public Criteria andNotifyStateGreaterThanOrEqualTo(String value) {
            addCriterion("notify_state >=", value, "notifyState");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: success表示成功，其他一切表示失败
        */
        public Criteria andNotifyStateLessThan(String value) {
            addCriterion("notify_state <", value, "notifyState");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: success表示成功，其他一切表示失败
        */
        public Criteria andNotifyStateLessThanOrEqualTo(String value) {
            addCriterion("notify_state <=", value, "notifyState");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: success表示成功，其他一切表示失败
        */
        public Criteria andNotifyStateLike(String value) {
            addCriterion("notify_state like", value, "notifyState");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: success表示成功，其他一切表示失败
        */
        public Criteria andNotifyStateNotLike(String value) {
            addCriterion("notify_state not like", value, "notifyState");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: success表示成功，其他一切表示失败
        */
        public Criteria andNotifyStateIn(List<String> values) {
            addCriterion("notify_state in", values, "notifyState");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: success表示成功，其他一切表示失败
        */
        public Criteria andNotifyStateNotIn(List<String> values) {
            addCriterion("notify_state not in", values, "notifyState");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: success表示成功，其他一切表示失败
        */
        public Criteria andNotifyStateBetween(String value1, String value2) {
            addCriterion("notify_state between", value1, value2, "notifyState");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: success表示成功，其他一切表示失败
        */
        public Criteria andNotifyStateNotBetween(String value1, String value2) {
            addCriterion("notify_state not between", value1, value2, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyBooknoIsNull() {
            addCriterion("notify_bookNo is null");
            return (Criteria) this;
        }

        public Criteria andNotifyBooknoIsNotNull() {
            addCriterion("notify_bookNo is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号唯一
        */
        public Criteria andNotifyBooknoEqualTo(String value) {
            addCriterion("notify_bookNo =", value, "notifyBookno");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号唯一
        */
        public Criteria andNotifyBooknoNotEqualTo(String value) {
            addCriterion("notify_bookNo <>", value, "notifyBookno");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号唯一
        */
        public Criteria andNotifyBooknoGreaterThan(String value) {
            addCriterion("notify_bookNo >", value, "notifyBookno");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号唯一
        */
        public Criteria andNotifyBooknoGreaterThanOrEqualTo(String value) {
            addCriterion("notify_bookNo >=", value, "notifyBookno");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号唯一
        */
        public Criteria andNotifyBooknoLessThan(String value) {
            addCriterion("notify_bookNo <", value, "notifyBookno");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号唯一
        */
        public Criteria andNotifyBooknoLessThanOrEqualTo(String value) {
            addCriterion("notify_bookNo <=", value, "notifyBookno");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号唯一
        */
        public Criteria andNotifyBooknoLike(String value) {
            addCriterion("notify_bookNo like", value, "notifyBookno");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号唯一
        */
        public Criteria andNotifyBooknoNotLike(String value) {
            addCriterion("notify_bookNo not like", value, "notifyBookno");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号唯一
        */
        public Criteria andNotifyBooknoIn(List<String> values) {
            addCriterion("notify_bookNo in", values, "notifyBookno");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号唯一
        */
        public Criteria andNotifyBooknoNotIn(List<String> values) {
            addCriterion("notify_bookNo not in", values, "notifyBookno");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号唯一
        */
        public Criteria andNotifyBooknoBetween(String value1, String value2) {
            addCriterion("notify_bookNo between", value1, value2, "notifyBookno");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 订单编号唯一
        */
        public Criteria andNotifyBooknoNotBetween(String value1, String value2) {
            addCriterion("notify_bookNo not between", value1, value2, "notifyBookno");
            return (Criteria) this;
        }

        public Criteria andNotifyPriceIsNull() {
            addCriterion("notify_price is null");
            return (Criteria) this;
        }

        public Criteria andNotifyPriceIsNotNull() {
            addCriterion("notify_price is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 交易额
        */
        public Criteria andNotifyPriceEqualTo(Float value) {
            addCriterion("notify_price =", value, "notifyPrice");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 交易额
        */
        public Criteria andNotifyPriceNotEqualTo(Float value) {
            addCriterion("notify_price <>", value, "notifyPrice");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 交易额
        */
        public Criteria andNotifyPriceGreaterThan(Float value) {
            addCriterion("notify_price >", value, "notifyPrice");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 交易额
        */
        public Criteria andNotifyPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("notify_price >=", value, "notifyPrice");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 交易额
        */
        public Criteria andNotifyPriceLessThan(Float value) {
            addCriterion("notify_price <", value, "notifyPrice");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 交易额
        */
        public Criteria andNotifyPriceLessThanOrEqualTo(Float value) {
            addCriterion("notify_price <=", value, "notifyPrice");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 交易额
        */
        public Criteria andNotifyPriceIn(List<Float> values) {
            addCriterion("notify_price in", values, "notifyPrice");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 交易额
        */
        public Criteria andNotifyPriceNotIn(List<Float> values) {
            addCriterion("notify_price not in", values, "notifyPrice");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 交易额
        */
        public Criteria andNotifyPriceBetween(Float value1, Float value2) {
            addCriterion("notify_price between", value1, value2, "notifyPrice");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 交易额
        */
        public Criteria andNotifyPriceNotBetween(Float value1, Float value2) {
            addCriterion("notify_price not between", value1, value2, "notifyPrice");
            return (Criteria) this;
        }

        public Criteria andNotifySyntypeIsNull() {
            addCriterion("notify_synType is null");
            return (Criteria) this;
        }

        public Criteria andNotifySyntypeIsNotNull() {
            addCriterion("notify_synType is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付类型刑
        */
        public Criteria andNotifySyntypeEqualTo(String value) {
            addCriterion("notify_synType =", value, "notifySyntype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付类型刑
        */
        public Criteria andNotifySyntypeNotEqualTo(String value) {
            addCriterion("notify_synType <>", value, "notifySyntype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付类型刑
        */
        public Criteria andNotifySyntypeGreaterThan(String value) {
            addCriterion("notify_synType >", value, "notifySyntype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付类型刑
        */
        public Criteria andNotifySyntypeGreaterThanOrEqualTo(String value) {
            addCriterion("notify_synType >=", value, "notifySyntype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付类型刑
        */
        public Criteria andNotifySyntypeLessThan(String value) {
            addCriterion("notify_synType <", value, "notifySyntype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付类型刑
        */
        public Criteria andNotifySyntypeLessThanOrEqualTo(String value) {
            addCriterion("notify_synType <=", value, "notifySyntype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付类型刑
        */
        public Criteria andNotifySyntypeLike(String value) {
            addCriterion("notify_synType like", value, "notifySyntype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付类型刑
        */
        public Criteria andNotifySyntypeNotLike(String value) {
            addCriterion("notify_synType not like", value, "notifySyntype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付类型刑
        */
        public Criteria andNotifySyntypeIn(List<String> values) {
            addCriterion("notify_synType in", values, "notifySyntype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付类型刑
        */
        public Criteria andNotifySyntypeNotIn(List<String> values) {
            addCriterion("notify_synType not in", values, "notifySyntype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付类型刑
        */
        public Criteria andNotifySyntypeBetween(String value1, String value2) {
            addCriterion("notify_synType between", value1, value2, "notifySyntype");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 支付类型刑
        */
        public Criteria andNotifySyntypeNotBetween(String value1, String value2) {
            addCriterion("notify_synType not between", value1, value2, "notifySyntype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_order_wiipay
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion() {
            super();
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}