package com.cheyooh.service.sdk.db.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SdkPropsSettingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    public SdkPropsSettingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 
        */
        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPropsNameIsNull() {
            addCriterion("props_name is null");
            return (Criteria) this;
        }

        public Criteria andPropsNameIsNotNull() {
            addCriterion("props_name is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具名称
        */
        public Criteria andPropsNameEqualTo(String value) {
            addCriterion("props_name =", value, "propsName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具名称
        */
        public Criteria andPropsNameNotEqualTo(String value) {
            addCriterion("props_name <>", value, "propsName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具名称
        */
        public Criteria andPropsNameGreaterThan(String value) {
            addCriterion("props_name >", value, "propsName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具名称
        */
        public Criteria andPropsNameGreaterThanOrEqualTo(String value) {
            addCriterion("props_name >=", value, "propsName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具名称
        */
        public Criteria andPropsNameLessThan(String value) {
            addCriterion("props_name <", value, "propsName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具名称
        */
        public Criteria andPropsNameLessThanOrEqualTo(String value) {
            addCriterion("props_name <=", value, "propsName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具名称
        */
        public Criteria andPropsNameLike(String value) {
            addCriterion("props_name like", value, "propsName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具名称
        */
        public Criteria andPropsNameNotLike(String value) {
            addCriterion("props_name not like", value, "propsName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具名称
        */
        public Criteria andPropsNameIn(List<String> values) {
            addCriterion("props_name in", values, "propsName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具名称
        */
        public Criteria andPropsNameNotIn(List<String> values) {
            addCriterion("props_name not in", values, "propsName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具名称
        */
        public Criteria andPropsNameBetween(String value1, String value2) {
            addCriterion("props_name between", value1, value2, "propsName");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具名称
        */
        public Criteria andPropsNameNotBetween(String value1, String value2) {
            addCriterion("props_name not between", value1, value2, "propsName");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 单价(元)
        */
        public Criteria andAmountEqualTo(Float value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 单价(元)
        */
        public Criteria andAmountNotEqualTo(Float value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 单价(元)
        */
        public Criteria andAmountGreaterThan(Float value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 单价(元)
        */
        public Criteria andAmountGreaterThanOrEqualTo(Float value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 单价(元)
        */
        public Criteria andAmountLessThan(Float value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 单价(元)
        */
        public Criteria andAmountLessThanOrEqualTo(Float value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 单价(元)
        */
        public Criteria andAmountIn(List<Float> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 单价(元)
        */
        public Criteria andAmountNotIn(List<Float> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 单价(元)
        */
        public Criteria andAmountBetween(Float value1, Float value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 单价(元)
        */
        public Criteria andAmountNotBetween(Float value1, Float value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andPropsDescIsNull() {
            addCriterion("props_desc is null");
            return (Criteria) this;
        }

        public Criteria andPropsDescIsNotNull() {
            addCriterion("props_desc is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具功能
        */
        public Criteria andPropsDescEqualTo(String value) {
            addCriterion("props_desc =", value, "propsDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具功能
        */
        public Criteria andPropsDescNotEqualTo(String value) {
            addCriterion("props_desc <>", value, "propsDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具功能
        */
        public Criteria andPropsDescGreaterThan(String value) {
            addCriterion("props_desc >", value, "propsDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具功能
        */
        public Criteria andPropsDescGreaterThanOrEqualTo(String value) {
            addCriterion("props_desc >=", value, "propsDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具功能
        */
        public Criteria andPropsDescLessThan(String value) {
            addCriterion("props_desc <", value, "propsDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具功能
        */
        public Criteria andPropsDescLessThanOrEqualTo(String value) {
            addCriterion("props_desc <=", value, "propsDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具功能
        */
        public Criteria andPropsDescLike(String value) {
            addCriterion("props_desc like", value, "propsDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具功能
        */
        public Criteria andPropsDescNotLike(String value) {
            addCriterion("props_desc not like", value, "propsDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具功能
        */
        public Criteria andPropsDescIn(List<String> values) {
            addCriterion("props_desc in", values, "propsDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具功能
        */
        public Criteria andPropsDescNotIn(List<String> values) {
            addCriterion("props_desc not in", values, "propsDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具功能
        */
        public Criteria andPropsDescBetween(String value1, String value2) {
            addCriterion("props_desc between", value1, value2, "propsDesc");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具功能
        */
        public Criteria andPropsDescNotBetween(String value1, String value2) {
            addCriterion("props_desc not between", value1, value2, "propsDesc");
            return (Criteria) this;
        }

        public Criteria andPropsAliasIsNull() {
            addCriterion("props_alias is null");
            return (Criteria) this;
        }

        public Criteria andPropsAliasIsNotNull() {
            addCriterion("props_alias is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具别名
        */
        public Criteria andPropsAliasEqualTo(String value) {
            addCriterion("props_alias =", value, "propsAlias");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具别名
        */
        public Criteria andPropsAliasNotEqualTo(String value) {
            addCriterion("props_alias <>", value, "propsAlias");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具别名
        */
        public Criteria andPropsAliasGreaterThan(String value) {
            addCriterion("props_alias >", value, "propsAlias");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具别名
        */
        public Criteria andPropsAliasGreaterThanOrEqualTo(String value) {
            addCriterion("props_alias >=", value, "propsAlias");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具别名
        */
        public Criteria andPropsAliasLessThan(String value) {
            addCriterion("props_alias <", value, "propsAlias");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具别名
        */
        public Criteria andPropsAliasLessThanOrEqualTo(String value) {
            addCriterion("props_alias <=", value, "propsAlias");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具别名
        */
        public Criteria andPropsAliasLike(String value) {
            addCriterion("props_alias like", value, "propsAlias");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具别名
        */
        public Criteria andPropsAliasNotLike(String value) {
            addCriterion("props_alias not like", value, "propsAlias");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具别名
        */
        public Criteria andPropsAliasIn(List<String> values) {
            addCriterion("props_alias in", values, "propsAlias");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具别名
        */
        public Criteria andPropsAliasNotIn(List<String> values) {
            addCriterion("props_alias not in", values, "propsAlias");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具别名
        */
        public Criteria andPropsAliasBetween(String value1, String value2) {
            addCriterion("props_alias between", value1, value2, "propsAlias");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具别名
        */
        public Criteria andPropsAliasNotBetween(String value1, String value2) {
            addCriterion("props_alias not between", value1, value2, "propsAlias");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 创建时间
        */
        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("updated_time is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeEqualTo(Date value) {
            addCriterion("updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeNotEqualTo(Date value) {
            addCriterion("updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeGreaterThan(Date value) {
            addCriterion("updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeLessThan(Date value) {
            addCriterion("updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeIn(List<Date> values) {
            addCriterion("updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeNotIn(List<Date> values) {
            addCriterion("updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 更改时间
        */
        public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andGameIdIsNull() {
            addCriterion("game_id is null");
            return (Criteria) this;
        }

        public Criteria andGameIdIsNotNull() {
            addCriterion("game_id is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏id
        */
        public Criteria andGameIdEqualTo(Integer value) {
            addCriterion("game_id =", value, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏id
        */
        public Criteria andGameIdNotEqualTo(Integer value) {
            addCriterion("game_id <>", value, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏id
        */
        public Criteria andGameIdGreaterThan(Integer value) {
            addCriterion("game_id >", value, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏id
        */
        public Criteria andGameIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("game_id >=", value, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏id
        */
        public Criteria andGameIdLessThan(Integer value) {
            addCriterion("game_id <", value, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏id
        */
        public Criteria andGameIdLessThanOrEqualTo(Integer value) {
            addCriterion("game_id <=", value, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏id
        */
        public Criteria andGameIdIn(List<Integer> values) {
            addCriterion("game_id in", values, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏id
        */
        public Criteria andGameIdNotIn(List<Integer> values) {
            addCriterion("game_id not in", values, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏id
        */
        public Criteria andGameIdBetween(Integer value1, Integer value2) {
            addCriterion("game_id between", value1, value2, "gameId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 游戏id
        */
        public Criteria andGameIdNotBetween(Integer value1, Integer value2) {
            addCriterion("game_id not between", value1, value2, "gameId");
            return (Criteria) this;
        }

        public Criteria andOperatorPayChannelIdIsNull() {
            addCriterion("operator_pay_channel_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorPayChannelIdIsNotNull() {
            addCriterion("operator_pay_channel_id is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商支付渠道配置id
        */
        public Criteria andOperatorPayChannelIdEqualTo(Integer value) {
            addCriterion("operator_pay_channel_id =", value, "operatorPayChannelId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商支付渠道配置id
        */
        public Criteria andOperatorPayChannelIdNotEqualTo(Integer value) {
            addCriterion("operator_pay_channel_id <>", value, "operatorPayChannelId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商支付渠道配置id
        */
        public Criteria andOperatorPayChannelIdGreaterThan(Integer value) {
            addCriterion("operator_pay_channel_id >", value, "operatorPayChannelId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商支付渠道配置id
        */
        public Criteria andOperatorPayChannelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("operator_pay_channel_id >=", value, "operatorPayChannelId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商支付渠道配置id
        */
        public Criteria andOperatorPayChannelIdLessThan(Integer value) {
            addCriterion("operator_pay_channel_id <", value, "operatorPayChannelId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商支付渠道配置id
        */
        public Criteria andOperatorPayChannelIdLessThanOrEqualTo(Integer value) {
            addCriterion("operator_pay_channel_id <=", value, "operatorPayChannelId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商支付渠道配置id
        */
        public Criteria andOperatorPayChannelIdIn(List<Integer> values) {
            addCriterion("operator_pay_channel_id in", values, "operatorPayChannelId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商支付渠道配置id
        */
        public Criteria andOperatorPayChannelIdNotIn(List<Integer> values) {
            addCriterion("operator_pay_channel_id not in", values, "operatorPayChannelId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商支付渠道配置id
        */
        public Criteria andOperatorPayChannelIdBetween(Integer value1, Integer value2) {
            addCriterion("operator_pay_channel_id between", value1, value2, "operatorPayChannelId");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 运营商支付渠道配置id
        */
        public Criteria andOperatorPayChannelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("operator_pay_channel_id not between", value1, value2, "operatorPayChannelId");
            return (Criteria) this;
        }

        public Criteria andUseStatusIsNull() {
            addCriterion("use_status is null");
            return (Criteria) this;
        }

        public Criteria andUseStatusIsNotNull() {
            addCriterion("use_status is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 使用状态，0：停用；1：使用
        */
        public Criteria andUseStatusEqualTo(Integer value) {
            addCriterion("use_status =", value, "useStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 使用状态，0：停用；1：使用
        */
        public Criteria andUseStatusNotEqualTo(Integer value) {
            addCriterion("use_status <>", value, "useStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 使用状态，0：停用；1：使用
        */
        public Criteria andUseStatusGreaterThan(Integer value) {
            addCriterion("use_status >", value, "useStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 使用状态，0：停用；1：使用
        */
        public Criteria andUseStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("use_status >=", value, "useStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 使用状态，0：停用；1：使用
        */
        public Criteria andUseStatusLessThan(Integer value) {
            addCriterion("use_status <", value, "useStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 使用状态，0：停用；1：使用
        */
        public Criteria andUseStatusLessThanOrEqualTo(Integer value) {
            addCriterion("use_status <=", value, "useStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 使用状态，0：停用；1：使用
        */
        public Criteria andUseStatusIn(List<Integer> values) {
            addCriterion("use_status in", values, "useStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 使用状态，0：停用；1：使用
        */
        public Criteria andUseStatusNotIn(List<Integer> values) {
            addCriterion("use_status not in", values, "useStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 使用状态，0：停用；1：使用
        */
        public Criteria andUseStatusBetween(Integer value1, Integer value2) {
            addCriterion("use_status between", value1, value2, "useStatus");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 使用状态，0：停用；1：使用
        */
        public Criteria andUseStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("use_status not between", value1, value2, "useStatus");
            return (Criteria) this;
        }

        public Criteria andPropsidIsNull() {
            addCriterion("propsid is null");
            return (Criteria) this;
        }

        public Criteria andPropsidIsNotNull() {
            addCriterion("propsid is not null");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具ID
        */
        public Criteria andPropsidEqualTo(String value) {
            addCriterion("propsid =", value, "propsid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具ID
        */
        public Criteria andPropsidNotEqualTo(String value) {
            addCriterion("propsid <>", value, "propsid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具ID
        */
        public Criteria andPropsidGreaterThan(String value) {
            addCriterion("propsid >", value, "propsid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具ID
        */
        public Criteria andPropsidGreaterThanOrEqualTo(String value) {
            addCriterion("propsid >=", value, "propsid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具ID
        */
        public Criteria andPropsidLessThan(String value) {
            addCriterion("propsid <", value, "propsid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具ID
        */
        public Criteria andPropsidLessThanOrEqualTo(String value) {
            addCriterion("propsid <=", value, "propsid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具ID
        */
        public Criteria andPropsidLike(String value) {
            addCriterion("propsid like", value, "propsid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具ID
        */
        public Criteria andPropsidNotLike(String value) {
            addCriterion("propsid not like", value, "propsid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具ID
        */
        public Criteria andPropsidIn(List<String> values) {
            addCriterion("propsid in", values, "propsid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具ID
        */
        public Criteria andPropsidNotIn(List<String> values) {
            addCriterion("propsid not in", values, "propsid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具ID
        */
        public Criteria andPropsidBetween(String value1, String value2) {
            addCriterion("propsid between", value1, value2, "propsid");
            return (Criteria) this;
        }

        /**<br/>
          * 字段说明: 道具ID
        */
        public Criteria andPropsidNotBetween(String value1, String value2) {
            addCriterion("propsid not between", value1, value2, "propsid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_props_setting
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdk_props_setting
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion() {
            super();
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}