package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGameShenzhoufu;
import com.cheyooh.service.sdk.db.entity.SdkGameShenzhoufuExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGameShenzhoufuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    int countByExample(SdkGameShenzhoufuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGameShenzhoufuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    int insert(SdkGameShenzhoufu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    int insertSelective(SdkGameShenzhoufu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    List<SdkGameShenzhoufu> selectByExample(SdkGameShenzhoufuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    Pagination<SdkGameShenzhoufu> selectByExample(SdkGameShenzhoufuExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    SdkGameShenzhoufu selectOne(SdkGameShenzhoufuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    SdkGameShenzhoufu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGameShenzhoufu record, @Param("example") SdkGameShenzhoufuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGameShenzhoufu record, @Param("example") SdkGameShenzhoufuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGameShenzhoufu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_shenzhoufu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGameShenzhoufu record);
}