package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkOrder;
import com.cheyooh.service.sdk.db.entity.SdkOrderExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    int countByExample(SdkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    int deleteByExample(SdkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    int insert(SdkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    int insertSelective(SdkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    List<SdkOrder> selectByExample(SdkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    Pagination<SdkOrder> selectByExample(SdkOrderExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    SdkOrder selectOne(SdkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    SdkOrder selectByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkOrder record, @Param("example") SdkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkOrder record, @Param("example") SdkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkOrder record);
}