package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkOperatorPayType;
import com.cheyooh.service.sdk.db.entity.SdkOperatorPayTypeExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkOperatorPayTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    int countByExample(SdkOperatorPayTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    int deleteByExample(SdkOperatorPayTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    int insert(SdkOperatorPayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    int insertSelective(SdkOperatorPayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    List<SdkOperatorPayType> selectByExample(SdkOperatorPayTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    Pagination<SdkOperatorPayType> selectByExample(SdkOperatorPayTypeExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    SdkOperatorPayType selectOne(SdkOperatorPayTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    SdkOperatorPayType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkOperatorPayType record, @Param("example") SdkOperatorPayTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkOperatorPayType record, @Param("example") SdkOperatorPayTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkOperatorPayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_operator_pay_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkOperatorPayType record);
}