package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkGamePayrepeat;
import com.cheyooh.service.sdk.db.entity.SdkGamePayrepeatExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkGamePayrepeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    int countByExample(SdkGamePayrepeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    int deleteByExample(SdkGamePayrepeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    int insert(SdkGamePayrepeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    int insertSelective(SdkGamePayrepeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    List<SdkGamePayrepeat> selectByExample(SdkGamePayrepeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    Pagination<SdkGamePayrepeat> selectByExample(SdkGamePayrepeatExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    SdkGamePayrepeat selectOne(SdkGamePayrepeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    SdkGamePayrepeat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkGamePayrepeat record, @Param("example") SdkGamePayrepeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkGamePayrepeat record, @Param("example") SdkGamePayrepeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkGamePayrepeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_game_payrepeat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkGamePayrepeat record);
}