package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkXuanwu;
import com.cheyooh.service.sdk.db.entity.SdkXuanwuExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkXuanwuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    int countByExample(SdkXuanwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    int deleteByExample(SdkXuanwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    int insert(SdkXuanwu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    int insertSelective(SdkXuanwu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    List<SdkXuanwu> selectByExample(SdkXuanwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    Pagination<SdkXuanwu> selectByExample(SdkXuanwuExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    SdkXuanwu selectOne(SdkXuanwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    SdkXuanwu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkXuanwu record, @Param("example") SdkXuanwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkXuanwu record, @Param("example") SdkXuanwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkXuanwu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_xuanwu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkXuanwu record);
}