package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkOrderUnionpay;
import com.cheyooh.service.sdk.db.entity.SdkOrderUnionpayExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkOrderUnionpayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    int countByExample(SdkOrderUnionpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    int deleteByExample(SdkOrderUnionpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    int insert(SdkOrderUnionpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    int insertSelective(SdkOrderUnionpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    List<SdkOrderUnionpay> selectByExample(SdkOrderUnionpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    Pagination<SdkOrderUnionpay> selectByExample(SdkOrderUnionpayExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    List<SdkOrderUnionpay> selectByExampleWithBLOBs(SdkOrderUnionpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    Pagination<SdkOrderUnionpay> selectByExampleWithBLOBs(SdkOrderUnionpayExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    SdkOrderUnionpay selectOne(SdkOrderUnionpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    SdkOrderUnionpay selectByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkOrderUnionpay record, @Param("example") SdkOrderUnionpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SdkOrderUnionpay record, @Param("example") SdkOrderUnionpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkOrderUnionpay record, @Param("example") SdkOrderUnionpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkOrderUnionpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SdkOrderUnionpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_unionpay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkOrderUnionpay record);
}