package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkOrderMmdo;
import com.cheyooh.service.sdk.db.entity.SdkOrderMmdoExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkOrderMmdoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    int countByExample(SdkOrderMmdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    int deleteByExample(SdkOrderMmdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    int insert(SdkOrderMmdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    int insertSelective(SdkOrderMmdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    List<SdkOrderMmdo> selectByExample(SdkOrderMmdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    Pagination<SdkOrderMmdo> selectByExample(SdkOrderMmdoExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    SdkOrderMmdo selectOne(SdkOrderMmdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    SdkOrderMmdo selectByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkOrderMmdo record, @Param("example") SdkOrderMmdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkOrderMmdo record, @Param("example") SdkOrderMmdoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkOrderMmdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_order_mmdo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkOrderMmdo record);
}