package com.cheyooh.service.sdk.db.dao;

import com.cheyooh.service.sdk.db.entity.SdkSms;
import com.cheyooh.service.sdk.db.entity.SdkSmsExample;
import com.cheyooh.tools.utils.Pagination;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdkSmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    int countByExample(SdkSmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    int deleteByExample(SdkSmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    int insert(SdkSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    int insertSelective(SdkSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    List<SdkSms> selectByExample(SdkSmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    Pagination<SdkSms> selectByExample(SdkSmsExample example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    SdkSms selectOne(SdkSmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    SdkSms selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SdkSms record, @Param("example") SdkSmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SdkSms record, @Param("example") SdkSmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_sms
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkSms record);
}